//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 10:29:11 AM CLT 
//


package bbr.b2b.regional.logistic.xml.int1846;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}accion"/>
 *         &lt;element ref="{}cancelado"/>
 *         &lt;element ref="{}tipo_lpn"/>
 *         &lt;element ref="{}num_ordencompra"/>
 *         &lt;element ref="{}num_linea"/>
 *         &lt;element ref="{}cod_producto"/>
 *         &lt;element ref="{}cantidad"/>
 *         &lt;element ref="{}unid_medida"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accion",
    "cancelado",
    "tipoLpn",
    "numOrdencompra",
    "numLinea",
    "codProducto",
    "cantidad",
    "unidMedida"
})
@XmlRootElement(name = "detalle")
public class Detalle {

    @XmlElement(required = true)
    protected String accion;
    @XmlElement(required = true)
    protected String cancelado;
    @XmlElement(name = "tipo_lpn", required = true)
    protected String tipoLpn;
    @XmlElement(name = "num_ordencompra", required = true)
    protected String numOrdencompra;
    @XmlElement(name = "num_linea")
    protected int numLinea;
    @XmlElement(name = "cod_producto", required = true)
    protected String codProducto;
    protected double cantidad;
    @XmlElement(name = "unid_medida", required = true)
    protected String unidMedida;

    /**
     * Gets the value of the accion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccion() {
        return accion;
    }

    /**
     * Sets the value of the accion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccion(String value) {
        this.accion = value;
    }

    /**
     * Gets the value of the cancelado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelado() {
        return cancelado;
    }

    /**
     * Sets the value of the cancelado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelado(String value) {
        this.cancelado = value;
    }

    /**
     * Gets the value of the tipoLpn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoLpn() {
        return tipoLpn;
    }

    /**
     * Sets the value of the tipoLpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoLpn(String value) {
        this.tipoLpn = value;
    }

    /**
     * Gets the value of the numOrdencompra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumOrdencompra() {
        return numOrdencompra;
    }

    /**
     * Sets the value of the numOrdencompra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumOrdencompra(String value) {
        this.numOrdencompra = value;
    }

    /**
     * Gets the value of the numLinea property.
     * 
     */
    public int getNumLinea() {
        return numLinea;
    }

    /**
     * Sets the value of the numLinea property.
     * 
     */
    public void setNumLinea(int value) {
        this.numLinea = value;
    }

    /**
     * Gets the value of the codProducto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodProducto() {
        return codProducto;
    }

    /**
     * Sets the value of the codProducto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodProducto(String value) {
        this.codProducto = value;
    }

    /**
     * Gets the value of the cantidad property.
     * 
     */
    public double getCantidad() {
        return cantidad;
    }

    /**
     * Sets the value of the cantidad property.
     * 
     */
    public void setCantidad(double value) {
        this.cantidad = value;
    }

    /**
     * Gets the value of the unidMedida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnidMedida() {
        return unidMedida;
    }

    /**
     * Sets the value of the unidMedida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnidMedida(String value) {
        this.unidMedida = value;
    }

}
