//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 10:29:11 AM CLT 
//


package bbr.b2b.regional.logistic.xml.int1846;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}origen"/>
 *         &lt;element ref="{}accion"/>
 *         &lt;element ref="{}tipo"/>
 *         &lt;element ref="{}id_compania"/>
 *         &lt;element ref="{}localizacion"/>
 *         &lt;element ref="{}tipo_origen"/>
 *         &lt;element ref="{}cancelado"/>
 *         &lt;element ref="{}numero_asn"/>
 *         &lt;element ref="{}tipo_asn"/>
 *         &lt;element ref="{}estado_asn"/>
 *         &lt;element ref="{}cod_proveedor"/>
 *         &lt;element ref="{}fecha_creacion"/>
 *         &lt;element ref="{}cliente"/>
 *         &lt;element ref="{}detalle_asn"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "origen",
    "accion",
    "tipo",
    "idCompania",
    "localizacion",
    "tipoOrigen",
    "cancelado",
    "numeroAsn",
    "tipoAsn",
    "estadoAsn",
    "codProveedor",
    "fechaCreacion",
    "cliente",
    "detalleAsn"
})
@XmlRootElement(name = "Message")
public class Message {

    @XmlElement(required = true)
    protected String origen;
    @XmlElement(required = true)
    protected String accion;
    @XmlElement(required = true)
    protected String tipo;
    @XmlElement(name = "id_compania", required = true)
    protected String idCompania;
    @XmlElement(required = true)
    protected String localizacion;
    @XmlElement(name = "tipo_origen", required = true)
    protected String tipoOrigen;
    @XmlElement(required = true)
    protected String cancelado;
    @XmlElement(name = "numero_asn", required = true)
    protected String numeroAsn;
    @XmlElement(name = "tipo_asn", required = true)
    protected String tipoAsn;
    @XmlElement(name = "estado_asn", required = true)
    protected String estadoAsn;
    @XmlElement(name = "cod_proveedor", required = true)
    protected String codProveedor;
    @XmlElement(name = "fecha_creacion", required = true)
    protected XMLGregorianCalendar fechaCreacion;
    @XmlElement(required = true)
    protected Cliente cliente;
    @XmlElement(name = "detalle_asn", required = true)
    protected DetalleAsn detalleAsn;

    /**
     * Gets the value of the origen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigen() {
        return origen;
    }

    /**
     * Sets the value of the origen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigen(String value) {
        this.origen = value;
    }

    /**
     * Gets the value of the accion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccion() {
        return accion;
    }

    /**
     * Sets the value of the accion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccion(String value) {
        this.accion = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the idCompania property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdCompania() {
        return idCompania;
    }

    /**
     * Sets the value of the idCompania property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdCompania(String value) {
        this.idCompania = value;
    }

    /**
     * Gets the value of the localizacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalizacion() {
        return localizacion;
    }

    /**
     * Sets the value of the localizacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalizacion(String value) {
        this.localizacion = value;
    }

    /**
     * Gets the value of the tipoOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoOrigen() {
        return tipoOrigen;
    }

    /**
     * Sets the value of the tipoOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoOrigen(String value) {
        this.tipoOrigen = value;
    }

    /**
     * Gets the value of the cancelado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelado() {
        return cancelado;
    }

    /**
     * Sets the value of the cancelado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelado(String value) {
        this.cancelado = value;
    }

    /**
     * Gets the value of the numeroAsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroAsn() {
        return numeroAsn;
    }

    /**
     * Sets the value of the numeroAsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroAsn(String value) {
        this.numeroAsn = value;
    }

    /**
     * Gets the value of the tipoAsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoAsn() {
        return tipoAsn;
    }

    /**
     * Sets the value of the tipoAsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoAsn(String value) {
        this.tipoAsn = value;
    }

    /**
     * Gets the value of the estadoAsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoAsn() {
        return estadoAsn;
    }

    /**
     * Sets the value of the estadoAsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoAsn(String value) {
        this.estadoAsn = value;
    }

    /**
     * Gets the value of the codProveedor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodProveedor() {
        return codProveedor;
    }

    /**
     * Sets the value of the codProveedor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodProveedor(String value) {
        this.codProveedor = value;
    }

    /**
     * Gets the value of the fechaCreacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaCreacion() {
        return fechaCreacion;
    }

    /**
     * Sets the value of the fechaCreacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaCreacion(XMLGregorianCalendar value) {
        this.fechaCreacion = value;
    }

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link Cliente }
     *     
     */
    public Cliente getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cliente }
     *     
     */
    public void setCliente(Cliente value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the detalleAsn property.
     * 
     * @return
     *     possible object is
     *     {@link DetalleAsn }
     *     
     */
    public DetalleAsn getDetalleAsn() {
        return detalleAsn;
    }

    /**
     * Sets the value of the detalleAsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetalleAsn }
     *     
     */
    public void setDetalleAsn(DetalleAsn value) {
        this.detalleAsn = value;
    }

}
