//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.19 at 04:59:42 PM CLT 
//


package bbr.b2b.regional.logistic.xml.qitem;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}secuencia"/>
 *         &lt;element ref="{}cod_producto"/>
 *         &lt;element ref="{}descripcion"/>
 *         &lt;element ref="{}codclase"/>
 *         &lt;element ref="{}descclase"/>
 *         &lt;element ref="{}codigobarraparis"/>
 *         &lt;element ref="{}cod_prov"/>
 *         &lt;element ref="{}cod_prod_prov" minOccurs="0"/>
 *         &lt;element ref="{}capacidad" minOccurs="0"/>
 *         &lt;element ref="{}lead_time" minOccurs="0"/>
 *         &lt;element ref="{}dimensiones" minOccurs="0"/>
 *         &lt;element ref="{}tipodeflujo"/>
 *         &lt;element ref="{}vev" minOccurs="0"/>
 *         &lt;element ref="{}innerpack"/>
 *         &lt;element ref="{}casepack"/>
 *         &lt;element ref="{}lista_ean" minOccurs="0"/>
 *         &lt;element ref="{}atc" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "secuencia",
    "codProducto",
    "descripcion",
    "codclase",
    "descclase",
    "codigobarraparis",
    "codProv",
    "codProdProv",
    "capacidad",
    "leadTime",
    "dimensiones",
    "tipodeflujo",
    "vev",
    "innerpack",
    "casepack",
    "listaEan",
    "atc"
})
@XmlRootElement(name = "QPRODUCTO")
public class QPRODUCTO {

    protected long secuencia;
    @XmlElement(name = "cod_producto", required = true)
    protected String codProducto;
    @XmlElement(required = true)
    protected String descripcion;
    @XmlElement(required = true)
    protected String codclase;
    @XmlElement(required = true)
    protected String descclase;
    @XmlElement(required = true)
    protected String codigobarraparis;
    @XmlElement(name = "cod_prov", required = true)
    protected String codProv;
    @XmlElement(name = "cod_prod_prov")
    protected String codProdProv;
    protected BigInteger capacidad;
    @XmlElement(name = "lead_time")
    protected Long leadTime;
    protected Dimensiones dimensiones;
    @XmlElement(required = true)
    protected String tipodeflujo;
    protected BigInteger vev;
    protected int innerpack;
    protected int casepack;
    @XmlElement(name = "lista_ean")
    protected ListaEan listaEan;
    protected Atc atc;

    /**
     * Gets the value of the secuencia property.
     * 
     */
    public long getSecuencia() {
        return secuencia;
    }

    /**
     * Sets the value of the secuencia property.
     * 
     */
    public void setSecuencia(long value) {
        this.secuencia = value;
    }

    /**
     * Gets the value of the codProducto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodProducto() {
        return codProducto;
    }

    /**
     * Sets the value of the codProducto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodProducto(String value) {
        this.codProducto = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

    /**
     * Gets the value of the codclase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodclase() {
        return codclase;
    }

    /**
     * Sets the value of the codclase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodclase(String value) {
        this.codclase = value;
    }

    /**
     * Gets the value of the descclase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescclase() {
        return descclase;
    }

    /**
     * Sets the value of the descclase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescclase(String value) {
        this.descclase = value;
    }

    /**
     * Gets the value of the codigobarraparis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigobarraparis() {
        return codigobarraparis;
    }

    /**
     * Sets the value of the codigobarraparis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigobarraparis(String value) {
        this.codigobarraparis = value;
    }

    /**
     * Gets the value of the codProv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodProv() {
        return codProv;
    }

    /**
     * Sets the value of the codProv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodProv(String value) {
        this.codProv = value;
    }

    /**
     * Gets the value of the codProdProv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodProdProv() {
        return codProdProv;
    }

    /**
     * Sets the value of the codProdProv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodProdProv(String value) {
        this.codProdProv = value;
    }

    /**
     * Gets the value of the capacidad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCapacidad() {
        return capacidad;
    }

    /**
     * Sets the value of the capacidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCapacidad(BigInteger value) {
        this.capacidad = value;
    }

    /**
     * Gets the value of the leadTime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLeadTime() {
        return leadTime;
    }

    /**
     * Sets the value of the leadTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLeadTime(Long value) {
        this.leadTime = value;
    }

    /**
     * Gets the value of the dimensiones property.
     * 
     * @return
     *     possible object is
     *     {@link Dimensiones }
     *     
     */
    public Dimensiones getDimensiones() {
        return dimensiones;
    }

    /**
     * Sets the value of the dimensiones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dimensiones }
     *     
     */
    public void setDimensiones(Dimensiones value) {
        this.dimensiones = value;
    }

    /**
     * Gets the value of the tipodeflujo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipodeflujo() {
        return tipodeflujo;
    }

    /**
     * Sets the value of the tipodeflujo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipodeflujo(String value) {
        this.tipodeflujo = value;
    }

    /**
     * Gets the value of the vev property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVev() {
        return vev;
    }

    /**
     * Sets the value of the vev property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVev(BigInteger value) {
        this.vev = value;
    }

    /**
     * Gets the value of the innerpack property.
     * 
     */
    public int getInnerpack() {
        return innerpack;
    }

    /**
     * Sets the value of the innerpack property.
     * 
     */
    public void setInnerpack(int value) {
        this.innerpack = value;
    }

    /**
     * Gets the value of the casepack property.
     * 
     */
    public int getCasepack() {
        return casepack;
    }

    /**
     * Sets the value of the casepack property.
     * 
     */
    public void setCasepack(int value) {
        this.casepack = value;
    }

    /**
     * Gets the value of the listaEan property.
     * 
     * @return
     *     possible object is
     *     {@link ListaEan }
     *     
     */
    public ListaEan getListaEan() {
        return listaEan;
    }

    /**
     * Sets the value of the listaEan property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaEan }
     *     
     */
    public void setListaEan(ListaEan value) {
        this.listaEan = value;
    }

    /**
     * Gets the value of the atc property.
     * 
     * @return
     *     possible object is
     *     {@link Atc }
     *     
     */
    public Atc getAtc() {
        return atc;
    }

    /**
     * Sets the value of the atc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Atc }
     *     
     */
    public void setAtc(Atc value) {
        this.atc = value;
    }

}
