package bbr.b2b.regional.logistic.evaluations.entities;

import java.util.Date;
import bbr.b2b.regional.logistic.datings.entities.Dating;
import bbr.b2b.regional.logistic.evaluations.data.interfaces.IReceptionEvaluation;

public class ReceptionEvaluation implements IReceptionEvaluation {

	private Long id;
	private Boolean autogenerated;
	private String who;
	private Date when;
	private Double score;
	private String comments;
	private Dating dating;

	public Long getId(){ 
		return this.id;
	}
	public Boolean getAutogenerated(){ 
		return this.autogenerated;
	}
	public String getWho(){ 
		return this.who;
	}
	public Date getWhen(){ 
		return this.when;
	}
	public Double getScore(){ 
		return this.score;
	}
	public String getComments(){ 
		return this.comments;
	}
	public Dating getDating(){ 
		return this.dating;
	}
	public void setId(Long id){ 
		this.id = id;
	}
	public void setAutogenerated(Boolean autogenerated){ 
		this.autogenerated = autogenerated;
	}
	public void setWho(String who){ 
		this.who = who;
	}
	public void setWhen(Date when){ 
		this.when = when;
	}
	public void setScore(Double score){ 
		this.score = score;
	}
	public void setComments(String comments){ 
		this.comments = comments;
	}
	public void setDating(Dating dating){ 
		this.dating = dating;
	}
}
