//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 01:06:07 PM CLT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://test.b2b.paris.cl/ParisLogisticaWeb/xsd/corden")
package bbr.b2b.regional.logistic.parser.loreal.order;
