//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 06:25:04 PM CLST 
//


package bbr.b2b.regional.logistic.xml.qorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}C0"/>
 *         &lt;element ref="{}C1"/>
 *         &lt;element ref="{}C2"/>
 *         &lt;element ref="{}C3" minOccurs="0"/>
 *         &lt;element ref="{}C4" minOccurs="0"/>
 *         &lt;element ref="{}C5" minOccurs="0"/>
 *         &lt;element ref="{}C6" minOccurs="0"/>
 *         &lt;element ref="{}C7" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "c0",
    "c1",
    "c2",
    "c3",
    "c4",
    "c5",
    "c6",
    "c7"
})
@XmlRootElement(name = "A3")
public class A3 {

    @XmlElement(name = "C0", required = true)
    protected String c0;
    @XmlElement(name = "C1", required = true)
    protected String c1;
    @XmlElement(name = "C2", required = true)
    protected String c2;
    @XmlElement(name = "C3")
    protected String c3;
    @XmlElement(name = "C4")
    protected String c4;
    @XmlElement(name = "C5")
    protected String c5;
    @XmlElement(name = "C6")
    protected String c6;
    @XmlElement(name = "C7")
    protected String c7;

    /**
     * Gets the value of the c0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC0() {
        return c0;
    }

    /**
     * Sets the value of the c0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC0(String value) {
        this.c0 = value;
    }

    /**
     * Gets the value of the c1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC1() {
        return c1;
    }

    /**
     * Sets the value of the c1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC1(String value) {
        this.c1 = value;
    }

    /**
     * Gets the value of the c2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC2() {
        return c2;
    }

    /**
     * Sets the value of the c2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC2(String value) {
        this.c2 = value;
    }

    /**
     * Gets the value of the c3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC3() {
        return c3;
    }

    /**
     * Sets the value of the c3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC3(String value) {
        this.c3 = value;
    }

    /**
     * Gets the value of the c4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC4() {
        return c4;
    }

    /**
     * Sets the value of the c4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC4(String value) {
        this.c4 = value;
    }

    /**
     * Gets the value of the c5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC5() {
        return c5;
    }

    /**
     * Sets the value of the c5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC5(String value) {
        this.c5 = value;
    }

    /**
     * Gets the value of the c6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC6() {
        return c6;
    }

    /**
     * Sets the value of the c6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC6(String value) {
        this.c6 = value;
    }

    /**
     * Gets the value of the c7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC7() {
        return c7;
    }

    /**
     * Sets the value of the c7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC7(String value) {
        this.c7 = value;
    }

}
