//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 06:25:04 PM CLST 
//


package bbr.b2b.regional.logistic.xml.qorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DC0"/>
 *         &lt;element ref="{}DC1"/>
 *         &lt;element ref="{}DC2" minOccurs="0"/>
 *         &lt;element ref="{}DC3" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dc0",
    "dc1",
    "dc2",
    "dc3"
})
@XmlRootElement(name = "DCS")
public class DCS {

    @XmlElement(name = "DC0")
    protected double dc0;
    @XmlElement(name = "DC1", required = true)
    protected String dc1;
    @XmlElement(name = "DC2")
    protected String dc2;
    @XmlElement(name = "DC3")
    protected String dc3;

    /**
     * Gets the value of the dc0 property.
     * 
     */
    public double getDC0() {
        return dc0;
    }

    /**
     * Sets the value of the dc0 property.
     * 
     */
    public void setDC0(double value) {
        this.dc0 = value;
    }

    /**
     * Gets the value of the dc1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDC1() {
        return dc1;
    }

    /**
     * Sets the value of the dc1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDC1(String value) {
        this.dc1 = value;
    }

    /**
     * Gets the value of the dc2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDC2() {
        return dc2;
    }

    /**
     * Sets the value of the dc2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDC2(String value) {
        this.dc2 = value;
    }

    /**
     * Gets the value of the dc3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDC3() {
        return dc3;
    }

    /**
     * Sets the value of the dc3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDC3(String value) {
        this.dc3 = value;
    }

}
