//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 06:25:04 PM CLST 
//


package bbr.b2b.regional.logistic.xml.qorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DI0"/>
 *         &lt;element ref="{}DI1"/>
 *         &lt;element ref="{}DI2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "di0",
    "di1",
    "di2"
})
@XmlRootElement(name = "DIS")
public class DIS {

    @XmlElement(name = "DI0", required = true)
    protected String di0;
    @XmlElement(name = "DI1", required = true)
    protected String di1;
    @XmlElement(name = "DI2", required = true)
    protected String di2;

    /**
     * Gets the value of the di0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDI0() {
        return di0;
    }

    /**
     * Sets the value of the di0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDI0(String value) {
        this.di0 = value;
    }

    /**
     * Gets the value of the di1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDI1() {
        return di1;
    }

    /**
     * Sets the value of the di1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDI1(String value) {
        this.di1 = value;
    }

    /**
     * Gets the value of the di2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDI2() {
        return di2;
    }

    /**
     * Sets the value of the di2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDI2(String value) {
        this.di2 = value;
    }

}
