//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 06:25:04 PM CLST 
//


package bbr.b2b.regional.logistic.xml.qorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DT0"/>
 *         &lt;element ref="{}DT1"/>
 *         &lt;element ref="{}DT2"/>
 *         &lt;element ref="{}DT3"/>
 *         &lt;element ref="{}DT4"/>
 *         &lt;element ref="{}DT5"/>
 *         &lt;element ref="{}DT6"/>
 *         &lt;element ref="{}DT7" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dt0",
    "dt1",
    "dt2",
    "dt3",
    "dt4",
    "dt5",
    "dt6",
    "dt7"
})
@XmlRootElement(name = "DTS")
public class DTS {

    @XmlElement(name = "DT0", required = true)
    protected String dt0;
    @XmlElement(name = "DT1")
    protected double dt1;
    @XmlElement(name = "DT2", required = true)
    protected String dt2;
    @XmlElement(name = "DT3")
    protected double dt3;
    @XmlElement(name = "DT4")
    protected double dt4;
    @XmlElement(name = "DT5")
    protected double dt5;
    @XmlElement(name = "DT6")
    protected double dt6;
    @XmlElement(name = "DT7")
    protected DT7 dt7;

    /**
     * Gets the value of the dt0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDT0() {
        return dt0;
    }

    /**
     * Sets the value of the dt0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDT0(String value) {
        this.dt0 = value;
    }

    /**
     * Gets the value of the dt1 property.
     * 
     */
    public double getDT1() {
        return dt1;
    }

    /**
     * Sets the value of the dt1 property.
     * 
     */
    public void setDT1(double value) {
        this.dt1 = value;
    }

    /**
     * Gets the value of the dt2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDT2() {
        return dt2;
    }

    /**
     * Sets the value of the dt2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDT2(String value) {
        this.dt2 = value;
    }

    /**
     * Gets the value of the dt3 property.
     * 
     */
    public double getDT3() {
        return dt3;
    }

    /**
     * Sets the value of the dt3 property.
     * 
     */
    public void setDT3(double value) {
        this.dt3 = value;
    }

    /**
     * Gets the value of the dt4 property.
     * 
     */
    public double getDT4() {
        return dt4;
    }

    /**
     * Sets the value of the dt4 property.
     * 
     */
    public void setDT4(double value) {
        this.dt4 = value;
    }

    /**
     * Gets the value of the dt5 property.
     * 
     */
    public double getDT5() {
        return dt5;
    }

    /**
     * Sets the value of the dt5 property.
     * 
     */
    public void setDT5(double value) {
        this.dt5 = value;
    }

    /**
     * Gets the value of the dt6 property.
     * 
     */
    public double getDT6() {
        return dt6;
    }

    /**
     * Sets the value of the dt6 property.
     * 
     */
    public void setDT6(double value) {
        this.dt6 = value;
    }

    /**
     * Gets the value of the dt7 property.
     * 
     * @return
     *     possible object is
     *     {@link DT7 }
     *     
     */
    public DT7 getDT7() {
        return dt7;
    }

    /**
     * Sets the value of the dt7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DT7 }
     *     
     */
    public void setDT7(DT7 value) {
        this.dt7 = value;
    }

}
