//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 06:25:04 PM CLST 
//


package bbr.b2b.regional.logistic.xml.qorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}L0"/>
 *         &lt;element ref="{}L1"/>
 *         &lt;element ref="{}L2"/>
 *         &lt;element ref="{}L3" minOccurs="0"/>
 *         &lt;element ref="{}L4" minOccurs="0"/>
 *         &lt;element ref="{}L5" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "l0",
    "l1",
    "l2",
    "l3",
    "l4",
    "l5"
})
@XmlRootElement(name = "LS")
public class LS {

    @XmlElement(name = "L0", required = true)
    protected String l0;
    @XmlElement(name = "L1", required = true)
    protected String l1;
    @XmlElement(name = "L2", required = true)
    protected String l2;
    @XmlElement(name = "L3")
    protected String l3;
    @XmlElement(name = "L4")
    protected String l4;
    @XmlElement(name = "L5")
    protected String l5;

    /**
     * Gets the value of the l0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getL0() {
        return l0;
    }

    /**
     * Sets the value of the l0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setL0(String value) {
        this.l0 = value;
    }

    /**
     * Gets the value of the l1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getL1() {
        return l1;
    }

    /**
     * Sets the value of the l1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setL1(String value) {
        this.l1 = value;
    }

    /**
     * Gets the value of the l2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getL2() {
        return l2;
    }

    /**
     * Sets the value of the l2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setL2(String value) {
        this.l2 = value;
    }

    /**
     * Gets the value of the l3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getL3() {
        return l3;
    }

    /**
     * Sets the value of the l3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setL3(String value) {
        this.l3 = value;
    }

    /**
     * Gets the value of the l4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getL4() {
        return l4;
    }

    /**
     * Sets the value of the l4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setL4(String value) {
        this.l4 = value;
    }

    /**
     * Gets the value of the l5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getL5() {
        return l5;
    }

    /**
     * Sets the value of the l5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setL5(String value) {
        this.l5 = value;
    }

}
