//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 06:25:04 PM CLST 
//


package bbr.b2b.regional.logistic.xml.qorder;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bbr.b2b.regional.logistic.xml.qorder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _A1_QNAME = new QName("", "A1");
    private final static QName _A6_QNAME = new QName("", "A6");
    private final static QName _A5_QNAME = new QName("", "A5");
    private final static QName _A8_QNAME = new QName("", "A8");
    private final static QName _A7_QNAME = new QName("", "A7");
    private final static QName _A9_QNAME = new QName("", "A9");
    private final static QName _PR14_QNAME = new QName("", "PR14");
    private final static QName _PD0_QNAME = new QName("", "PD0");
    private final static QName _PR12_QNAME = new QName("", "PR12");
    private final static QName _PD1_QNAME = new QName("", "PD1");
    private final static QName _PR11_QNAME = new QName("", "PR11");
    private final static QName _PD2_QNAME = new QName("", "PD2");
    private final static QName _PR10_QNAME = new QName("", "PR10");
    private final static QName _PD3_QNAME = new QName("", "PD3");
    private final static QName _E0_QNAME = new QName("", "E0");
    private final static QName _R2_QNAME = new QName("", "R2");
    private final static QName _CL10_QNAME = new QName("", "CL10");
    private final static QName _A0_QNAME = new QName("", "A0");
    private final static QName _B4_QNAME = new QName("", "B4");
    private final static QName _CL9_QNAME = new QName("", "CL9");
    private final static QName _R1_QNAME = new QName("", "R1");
    private final static QName _R0_QNAME = new QName("", "R0");
    private final static QName _CL0_QNAME = new QName("", "CL0");
    private final static QName _DT0_QNAME = new QName("", "DT0");
    private final static QName _CL7_QNAME = new QName("", "CL7");
    private final static QName _DT1_QNAME = new QName("", "DT1");
    private final static QName _CL8_QNAME = new QName("", "CL8");
    private final static QName _DT2_QNAME = new QName("", "DT2");
    private final static QName _CL5_QNAME = new QName("", "CL5");
    private final static QName _DT3_QNAME = new QName("", "DT3");
    private final static QName _CL6_QNAME = new QName("", "CL6");
    private final static QName _B0_QNAME = new QName("", "B0");
    private final static QName _DT4_QNAME = new QName("", "DT4");
    private final static QName _CL3_QNAME = new QName("", "CL3");
    private final static QName _B1_QNAME = new QName("", "B1");
    private final static QName _DT5_QNAME = new QName("", "DT5");
    private final static QName _CL4_QNAME = new QName("", "CL4");
    private final static QName _DT6_QNAME = new QName("", "DT6");
    private final static QName _CL1_QNAME = new QName("", "CL1");
    private final static QName _CL2_QNAME = new QName("", "CL2");
    private final static QName _C7_QNAME = new QName("", "C7");
    private final static QName _C4_QNAME = new QName("", "C4");
    private final static QName _C3_QNAME = new QName("", "C3");
    private final static QName _C6_QNAME = new QName("", "C6");
    private final static QName _C5_QNAME = new QName("", "C5");
    private final static QName _DI2_QNAME = new QName("", "DI2");
    private final static QName _DI1_QNAME = new QName("", "DI1");
    private final static QName _DI0_QNAME = new QName("", "DI0");
    private final static QName _ATC1_QNAME = new QName("", "ATC1");
    private final static QName _ATC0_QNAME = new QName("", "ATC0");
    private final static QName _C0_QNAME = new QName("", "C0");
    private final static QName _C1_QNAME = new QName("", "C1");
    private final static QName _C2_QNAME = new QName("", "C2");
    private final static QName _L0_QNAME = new QName("", "L0");
    private final static QName _L1_QNAME = new QName("", "L1");
    private final static QName _L2_QNAME = new QName("", "L2");
    private final static QName _L3_QNAME = new QName("", "L3");
    private final static QName _PR3_QNAME = new QName("", "PR3");
    private final static QName _P5_QNAME = new QName("", "P5");
    private final static QName _PR2_QNAME = new QName("", "PR2");
    private final static QName _P4_QNAME = new QName("", "P4");
    private final static QName _PR5_QNAME = new QName("", "PR5");
    private final static QName _P7_QNAME = new QName("", "P7");
    private final static QName _PR4_QNAME = new QName("", "PR4");
    private final static QName _P6_QNAME = new QName("", "P6");
    private final static QName _PR7_QNAME = new QName("", "PR7");
    private final static QName _L4_QNAME = new QName("", "L4");
    private final static QName _P1_QNAME = new QName("", "P1");
    private final static QName _PR6_QNAME = new QName("", "PR6");
    private final static QName _L5_QNAME = new QName("", "L5");
    private final static QName _P0_QNAME = new QName("", "P0");
    private final static QName _P3_QNAME = new QName("", "P3");
    private final static QName _P2_QNAME = new QName("", "P2");
    private final static QName _DC3_QNAME = new QName("", "DC3");
    private final static QName _DC2_QNAME = new QName("", "DC2");
    private final static QName _DC1_QNAME = new QName("", "DC1");
    private final static QName _PR0_QNAME = new QName("", "PR0");
    private final static QName _DC0_QNAME = new QName("", "DC0");
    private final static QName _PR1_QNAME = new QName("", "PR1");
    private final static QName _A13_QNAME = new QName("", "A13");
    private final static QName _D0_QNAME = new QName("", "D0");
    private final static QName _D1_QNAME = new QName("", "D1");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bbr.b2b.regional.logistic.xml.qorder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LS }
     * 
     */
    public LS createLS() {
        return new LS();
    }

    /**
     * Create an instance of {@link DT7 }
     * 
     */
    public DT7 createDT7() {
        return new DT7();
    }

    /**
     * Create an instance of {@link DCS }
     * 
     */
    public DCS createDCS() {
        return new DCS();
    }

    /**
     * Create an instance of {@link QORDEN }
     * 
     */
    public QORDEN createQORDEN() {
        return new QORDEN();
    }

    /**
     * Create an instance of {@link A2 }
     * 
     */
    public A2 createA2() {
        return new A2();
    }

    /**
     * Create an instance of {@link B2 }
     * 
     */
    public B2 createB2() {
        return new B2();
    }

    /**
     * Create an instance of {@link B3 }
     * 
     */
    public B3 createB3() {
        return new B3();
    }

    /**
     * Create an instance of {@link A3 }
     * 
     */
    public A3 createA3() {
        return new A3();
    }

    /**
     * Create an instance of {@link A4 }
     * 
     */
    public A4 createA4() {
        return new A4();
    }

    /**
     * Create an instance of {@link A10 }
     * 
     */
    public A10 createA10() {
        return new A10();
    }

    /**
     * Create an instance of {@link A11 }
     * 
     */
    public A11 createA11() {
        return new A11();
    }

    /**
     * Create an instance of {@link A12 }
     * 
     */
    public A12 createA12() {
        return new A12();
    }

    /**
     * Create an instance of {@link PRS }
     * 
     */
    public PRS createPRS() {
        return new PRS();
    }

    /**
     * Create an instance of {@link PR8 }
     * 
     */
    public PR8 createPR8() {
        return new PR8();
    }

    /**
     * Create an instance of {@link DIS }
     * 
     */
    public DIS createDIS() {
        return new DIS();
    }

    /**
     * Create an instance of {@link PR9 }
     * 
     */
    public PR9 createPR9() {
        return new PR9();
    }

    /**
     * Create an instance of {@link PR13 }
     * 
     */
    public PR13 createPR13() {
        return new PR13();
    }

    /**
     * Create an instance of {@link A14 }
     * 
     */
    public A14 createA14() {
        return new A14();
    }

    /**
     * Create an instance of {@link A15 }
     * 
     */
    public A15 createA15() {
        return new A15();
    }

    /**
     * Create an instance of {@link DTS }
     * 
     */
    public DTS createDTS() {
        return new DTS();
    }

    /**
     * Create an instance of {@link A16 }
     * 
     */
    public A16 createA16() {
        return new A16();
    }

    /**
     * Create an instance of {@link PDS }
     * 
     */
    public PDS createPDS() {
        return new PDS();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "A1")
    public JAXBElement<Long> createA1(Long value) {
        return new JAXBElement<Long>(_A1_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "A6")
    public JAXBElement<String> createA6(String value) {
        return new JAXBElement<String>(_A6_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "A5")
    public JAXBElement<String> createA5(String value) {
        return new JAXBElement<String>(_A5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "A8")
    public JAXBElement<String> createA8(String value) {
        return new JAXBElement<String>(_A8_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "A7")
    public JAXBElement<String> createA7(String value) {
        return new JAXBElement<String>(_A7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "A9")
    public JAXBElement<String> createA9(String value) {
        return new JAXBElement<String>(_A9_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR14")
    public JAXBElement<String> createPR14(String value) {
        return new JAXBElement<String>(_PR14_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PD0")
    public JAXBElement<String> createPD0(String value) {
        return new JAXBElement<String>(_PD0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR12")
    public JAXBElement<Integer> createPR12(Integer value) {
        return new JAXBElement<Integer>(_PR12_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PD1")
    public JAXBElement<String> createPD1(String value) {
        return new JAXBElement<String>(_PD1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR11")
    public JAXBElement<Integer> createPR11(Integer value) {
        return new JAXBElement<Integer>(_PR11_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PD2")
    public JAXBElement<Double> createPD2(Double value) {
        return new JAXBElement<Double>(_PD2_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR10")
    public JAXBElement<String> createPR10(String value) {
        return new JAXBElement<String>(_PR10_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PD3")
    public JAXBElement<Long> createPD3(Long value) {
        return new JAXBElement<Long>(_PD3_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E0")
    public JAXBElement<String> createE0(String value) {
        return new JAXBElement<String>(_E0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R2")
    public JAXBElement<String> createR2(String value) {
        return new JAXBElement<String>(_R2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CL10")
    public JAXBElement<String> createCL10(String value) {
        return new JAXBElement<String>(_CL10_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "A0")
    public JAXBElement<Long> createA0(Long value) {
        return new JAXBElement<Long>(_A0_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B4")
    public JAXBElement<String> createB4(String value) {
        return new JAXBElement<String>(_B4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CL9")
    public JAXBElement<String> createCL9(String value) {
        return new JAXBElement<String>(_CL9_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R1")
    public JAXBElement<String> createR1(String value) {
        return new JAXBElement<String>(_R1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R0")
    public JAXBElement<String> createR0(String value) {
        return new JAXBElement<String>(_R0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CL0")
    public JAXBElement<String> createCL0(String value) {
        return new JAXBElement<String>(_CL0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DT0")
    public JAXBElement<String> createDT0(String value) {
        return new JAXBElement<String>(_DT0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CL7")
    public JAXBElement<String> createCL7(String value) {
        return new JAXBElement<String>(_CL7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DT1")
    public JAXBElement<Double> createDT1(Double value) {
        return new JAXBElement<Double>(_DT1_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CL8")
    public JAXBElement<String> createCL8(String value) {
        return new JAXBElement<String>(_CL8_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DT2")
    public JAXBElement<String> createDT2(String value) {
        return new JAXBElement<String>(_DT2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CL5")
    public JAXBElement<String> createCL5(String value) {
        return new JAXBElement<String>(_CL5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DT3")
    public JAXBElement<Double> createDT3(Double value) {
        return new JAXBElement<Double>(_DT3_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CL6")
    public JAXBElement<String> createCL6(String value) {
        return new JAXBElement<String>(_CL6_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B0")
    public JAXBElement<String> createB0(String value) {
        return new JAXBElement<String>(_B0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DT4")
    public JAXBElement<Double> createDT4(Double value) {
        return new JAXBElement<Double>(_DT4_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CL3")
    public JAXBElement<String> createCL3(String value) {
        return new JAXBElement<String>(_CL3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B1")
    public JAXBElement<String> createB1(String value) {
        return new JAXBElement<String>(_B1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DT5")
    public JAXBElement<Double> createDT5(Double value) {
        return new JAXBElement<Double>(_DT5_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CL4")
    public JAXBElement<String> createCL4(String value) {
        return new JAXBElement<String>(_CL4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DT6")
    public JAXBElement<Double> createDT6(Double value) {
        return new JAXBElement<Double>(_DT6_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CL1")
    public JAXBElement<String> createCL1(String value) {
        return new JAXBElement<String>(_CL1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CL2")
    public JAXBElement<String> createCL2(String value) {
        return new JAXBElement<String>(_CL2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C7")
    public JAXBElement<String> createC7(String value) {
        return new JAXBElement<String>(_C7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C4")
    public JAXBElement<String> createC4(String value) {
        return new JAXBElement<String>(_C4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C3")
    public JAXBElement<String> createC3(String value) {
        return new JAXBElement<String>(_C3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C6")
    public JAXBElement<String> createC6(String value) {
        return new JAXBElement<String>(_C6_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C5")
    public JAXBElement<String> createC5(String value) {
        return new JAXBElement<String>(_C5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DI2")
    public JAXBElement<String> createDI2(String value) {
        return new JAXBElement<String>(_DI2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DI1")
    public JAXBElement<String> createDI1(String value) {
        return new JAXBElement<String>(_DI1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DI0")
    public JAXBElement<String> createDI0(String value) {
        return new JAXBElement<String>(_DI0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ATC1")
    public JAXBElement<Integer> createATC1(Integer value) {
        return new JAXBElement<Integer>(_ATC1_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ATC0")
    public JAXBElement<String> createATC0(String value) {
        return new JAXBElement<String>(_ATC0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C0")
    public JAXBElement<String> createC0(String value) {
        return new JAXBElement<String>(_C0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C1")
    public JAXBElement<String> createC1(String value) {
        return new JAXBElement<String>(_C1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C2")
    public JAXBElement<String> createC2(String value) {
        return new JAXBElement<String>(_C2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "L0")
    public JAXBElement<String> createL0(String value) {
        return new JAXBElement<String>(_L0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "L1")
    public JAXBElement<String> createL1(String value) {
        return new JAXBElement<String>(_L1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "L2")
    public JAXBElement<String> createL2(String value) {
        return new JAXBElement<String>(_L2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "L3")
    public JAXBElement<String> createL3(String value) {
        return new JAXBElement<String>(_L3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR3")
    public JAXBElement<String> createPR3(String value) {
        return new JAXBElement<String>(_PR3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "P5")
    public JAXBElement<String> createP5(String value) {
        return new JAXBElement<String>(_P5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR2")
    public JAXBElement<String> createPR2(String value) {
        return new JAXBElement<String>(_PR2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "P4")
    public JAXBElement<String> createP4(String value) {
        return new JAXBElement<String>(_P4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR5")
    public JAXBElement<String> createPR5(String value) {
        return new JAXBElement<String>(_PR5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "P7")
    public JAXBElement<String> createP7(String value) {
        return new JAXBElement<String>(_P7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR4")
    public JAXBElement<String> createPR4(String value) {
        return new JAXBElement<String>(_PR4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "P6")
    public JAXBElement<String> createP6(String value) {
        return new JAXBElement<String>(_P6_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR7")
    public JAXBElement<Long> createPR7(Long value) {
        return new JAXBElement<Long>(_PR7_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "L4")
    public JAXBElement<String> createL4(String value) {
        return new JAXBElement<String>(_L4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "P1")
    public JAXBElement<String> createP1(String value) {
        return new JAXBElement<String>(_P1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR6")
    public JAXBElement<Integer> createPR6(Integer value) {
        return new JAXBElement<Integer>(_PR6_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "L5")
    public JAXBElement<String> createL5(String value) {
        return new JAXBElement<String>(_L5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "P0")
    public JAXBElement<String> createP0(String value) {
        return new JAXBElement<String>(_P0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "P3")
    public JAXBElement<String> createP3(String value) {
        return new JAXBElement<String>(_P3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "P2")
    public JAXBElement<String> createP2(String value) {
        return new JAXBElement<String>(_P2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DC3")
    public JAXBElement<String> createDC3(String value) {
        return new JAXBElement<String>(_DC3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DC2")
    public JAXBElement<String> createDC2(String value) {
        return new JAXBElement<String>(_DC2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DC1")
    public JAXBElement<String> createDC1(String value) {
        return new JAXBElement<String>(_DC1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR0")
    public JAXBElement<String> createPR0(String value) {
        return new JAXBElement<String>(_PR0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DC0")
    public JAXBElement<Double> createDC0(Double value) {
        return new JAXBElement<Double>(_DC0_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PR1")
    public JAXBElement<String> createPR1(String value) {
        return new JAXBElement<String>(_PR1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "A13")
    public JAXBElement<String> createA13(String value) {
        return new JAXBElement<String>(_A13_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "D0")
    public JAXBElement<String> createD0(String value) {
        return new JAXBElement<String>(_D0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "D1")
    public JAXBElement<String> createD1(String value) {
        return new JAXBElement<String>(_D1_QNAME, String.class, null, value);
    }

}
