//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 06:25:04 PM CLST 
//


package bbr.b2b.regional.logistic.xml.qorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PD0"/>
 *         &lt;element ref="{}PD1"/>
 *         &lt;element ref="{}PD2"/>
 *         &lt;element ref="{}PD3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pd0",
    "pd1",
    "pd2",
    "pd3"
})
@XmlRootElement(name = "PDS")
public class PDS {

    @XmlElement(name = "PD0", required = true)
    protected String pd0;
    @XmlElement(name = "PD1", required = true)
    protected String pd1;
    @XmlElement(name = "PD2")
    protected double pd2;
    @XmlElement(name = "PD3")
    protected long pd3;

    /**
     * Gets the value of the pd0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPD0() {
        return pd0;
    }

    /**
     * Sets the value of the pd0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPD0(String value) {
        this.pd0 = value;
    }

    /**
     * Gets the value of the pd1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPD1() {
        return pd1;
    }

    /**
     * Sets the value of the pd1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPD1(String value) {
        this.pd1 = value;
    }

    /**
     * Gets the value of the pd2 property.
     * 
     */
    public double getPD2() {
        return pd2;
    }

    /**
     * Sets the value of the pd2 property.
     * 
     */
    public void setPD2(double value) {
        this.pd2 = value;
    }

    /**
     * Gets the value of the pd3 property.
     * 
     */
    public long getPD3() {
        return pd3;
    }

    /**
     * Sets the value of the pd3 property.
     * 
     */
    public void setPD3(long value) {
        this.pd3 = value;
    }

}
