//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 06:25:04 PM CLST 
//


package bbr.b2b.regional.logistic.xml.qorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PR0"/>
 *         &lt;element ref="{}PR1"/>
 *         &lt;element ref="{}PR2"/>
 *         &lt;element ref="{}PR3"/>
 *         &lt;element ref="{}PR4"/>
 *         &lt;element ref="{}PR5" minOccurs="0"/>
 *         &lt;element ref="{}PR6" minOccurs="0"/>
 *         &lt;element ref="{}PR7" minOccurs="0"/>
 *         &lt;element ref="{}PR8" minOccurs="0"/>
 *         &lt;element ref="{}PR9" minOccurs="0"/>
 *         &lt;element ref="{}PR10"/>
 *         &lt;element ref="{}PR11"/>
 *         &lt;element ref="{}PR12"/>
 *         &lt;element ref="{}PR13" minOccurs="0"/>
 *         &lt;element ref="{}PR14" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pr0",
    "pr1",
    "pr2",
    "pr3",
    "pr4",
    "pr5",
    "pr6",
    "pr7",
    "pr8",
    "pr9",
    "pr10",
    "pr11",
    "pr12",
    "pr13",
    "pr14"
})
@XmlRootElement(name = "PRS")
public class PRS {

    @XmlElement(name = "PR0", required = true)
    protected String pr0;
    @XmlElement(name = "PR1", required = true)
    protected String pr1;
    @XmlElement(name = "PR2", required = true)
    protected String pr2;
    @XmlElement(name = "PR3", required = true)
    protected String pr3;
    @XmlElement(name = "PR4", required = true)
    protected String pr4;
    @XmlElement(name = "PR5")
    protected String pr5;
    @XmlElement(name = "PR6")
    protected Integer pr6;
    @XmlElement(name = "PR7")
    protected Long pr7;
    @XmlElement(name = "PR8")
    protected PR8 pr8;
    @XmlElement(name = "PR9")
    protected PR9 pr9;
    @XmlElement(name = "PR10", required = true)
    protected String pr10;
    @XmlElement(name = "PR11")
    protected int pr11;
    @XmlElement(name = "PR12")
    protected int pr12;
    @XmlElement(name = "PR13")
    protected PR13 pr13;
    @XmlElement(name = "PR14")
    protected String pr14;

    /**
     * Gets the value of the pr0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPR0() {
        return pr0;
    }

    /**
     * Sets the value of the pr0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPR0(String value) {
        this.pr0 = value;
    }

    /**
     * Gets the value of the pr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPR1() {
        return pr1;
    }

    /**
     * Sets the value of the pr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPR1(String value) {
        this.pr1 = value;
    }

    /**
     * Gets the value of the pr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPR2() {
        return pr2;
    }

    /**
     * Sets the value of the pr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPR2(String value) {
        this.pr2 = value;
    }

    /**
     * Gets the value of the pr3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPR3() {
        return pr3;
    }

    /**
     * Sets the value of the pr3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPR3(String value) {
        this.pr3 = value;
    }

    /**
     * Gets the value of the pr4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPR4() {
        return pr4;
    }

    /**
     * Sets the value of the pr4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPR4(String value) {
        this.pr4 = value;
    }

    /**
     * Gets the value of the pr5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPR5() {
        return pr5;
    }

    /**
     * Sets the value of the pr5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPR5(String value) {
        this.pr5 = value;
    }

    /**
     * Gets the value of the pr6 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPR6() {
        return pr6;
    }

    /**
     * Sets the value of the pr6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPR6(Integer value) {
        this.pr6 = value;
    }

    /**
     * Gets the value of the pr7 property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPR7() {
        return pr7;
    }

    /**
     * Sets the value of the pr7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPR7(Long value) {
        this.pr7 = value;
    }

    /**
     * Gets the value of the pr8 property.
     * 
     * @return
     *     possible object is
     *     {@link PR8 }
     *     
     */
    public PR8 getPR8() {
        return pr8;
    }

    /**
     * Sets the value of the pr8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PR8 }
     *     
     */
    public void setPR8(PR8 value) {
        this.pr8 = value;
    }

    /**
     * Gets the value of the pr9 property.
     * 
     * @return
     *     possible object is
     *     {@link PR9 }
     *     
     */
    public PR9 getPR9() {
        return pr9;
    }

    /**
     * Sets the value of the pr9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PR9 }
     *     
     */
    public void setPR9(PR9 value) {
        this.pr9 = value;
    }

    /**
     * Gets the value of the pr10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPR10() {
        return pr10;
    }

    /**
     * Sets the value of the pr10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPR10(String value) {
        this.pr10 = value;
    }

    /**
     * Gets the value of the pr11 property.
     * 
     */
    public int getPR11() {
        return pr11;
    }

    /**
     * Sets the value of the pr11 property.
     * 
     */
    public void setPR11(int value) {
        this.pr11 = value;
    }

    /**
     * Gets the value of the pr12 property.
     * 
     */
    public int getPR12() {
        return pr12;
    }

    /**
     * Sets the value of the pr12 property.
     * 
     */
    public void setPR12(int value) {
        this.pr12 = value;
    }

    /**
     * Gets the value of the pr13 property.
     * 
     * @return
     *     possible object is
     *     {@link PR13 }
     *     
     */
    public PR13 getPR13() {
        return pr13;
    }

    /**
     * Sets the value of the pr13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PR13 }
     *     
     */
    public void setPR13(PR13 value) {
        this.pr13 = value;
    }

    /**
     * Gets the value of the pr14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPR14() {
        return pr14;
    }

    /**
     * Sets the value of the pr14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPR14(String value) {
        this.pr14 = value;
    }

}
