//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 06:25:04 PM CLST 
//


package bbr.b2b.regional.logistic.xml.qorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}A0"/>
 *         &lt;element ref="{}A1"/>
 *         &lt;element ref="{}A2" minOccurs="0"/>
 *         &lt;element ref="{}A3"/>
 *         &lt;element ref="{}A4"/>
 *         &lt;element ref="{}A5"/>
 *         &lt;element ref="{}A6"/>
 *         &lt;element ref="{}A7"/>
 *         &lt;element ref="{}A8" minOccurs="0"/>
 *         &lt;element ref="{}A9"/>
 *         &lt;element ref="{}A10"/>
 *         &lt;element ref="{}A11"/>
 *         &lt;element ref="{}A12"/>
 *         &lt;element ref="{}A13"/>
 *         &lt;element ref="{}A14" minOccurs="0"/>
 *         &lt;element ref="{}A15"/>
 *         &lt;element ref="{}A16"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "a0",
    "a1",
    "a2",
    "a3",
    "a4",
    "a5",
    "a6",
    "a7",
    "a8",
    "a9",
    "a10",
    "a11",
    "a12",
    "a13",
    "a14",
    "a15",
    "a16"
})
@XmlRootElement(name = "QORDEN")
public class QORDEN {

    @XmlElement(name = "A0")
    protected long a0;
    @XmlElement(name = "A1")
    protected long a1;
    @XmlElement(name = "A2")
    protected A2 a2;
    @XmlElement(name = "A3", required = true)
    protected A3 a3;
    @XmlElement(name = "A4", required = true)
    protected A4 a4;
    @XmlElement(name = "A5", required = true)
    protected String a5;
    @XmlElement(name = "A6", required = true)
    protected String a6;
    @XmlElement(name = "A7", required = true)
    protected String a7;
    @XmlElement(name = "A8")
    protected String a8;
    @XmlElement(name = "A9", required = true)
    protected String a9;
    @XmlElement(name = "A10", required = true)
    protected A10 a10;
    @XmlElement(name = "A11", required = true)
    protected A11 a11;
    @XmlElement(name = "A12", required = true)
    protected A12 a12;
    @XmlElement(name = "A13", required = true)
    protected String a13;
    @XmlElement(name = "A14")
    protected A14 a14;
    @XmlElement(name = "A15", required = true)
    protected A15 a15;
    @XmlElement(name = "A16", required = true)
    protected A16 a16;

    /**
     * Gets the value of the a0 property.
     * 
     */
    public long getA0() {
        return a0;
    }

    /**
     * Sets the value of the a0 property.
     * 
     */
    public void setA0(long value) {
        this.a0 = value;
    }

    /**
     * Gets the value of the a1 property.
     * 
     */
    public long getA1() {
        return a1;
    }

    /**
     * Sets the value of the a1 property.
     * 
     */
    public void setA1(long value) {
        this.a1 = value;
    }

    /**
     * Gets the value of the a2 property.
     * 
     * @return
     *     possible object is
     *     {@link A2 }
     *     
     */
    public A2 getA2() {
        return a2;
    }

    /**
     * Sets the value of the a2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link A2 }
     *     
     */
    public void setA2(A2 value) {
        this.a2 = value;
    }

    /**
     * Gets the value of the a3 property.
     * 
     * @return
     *     possible object is
     *     {@link A3 }
     *     
     */
    public A3 getA3() {
        return a3;
    }

    /**
     * Sets the value of the a3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link A3 }
     *     
     */
    public void setA3(A3 value) {
        this.a3 = value;
    }

    /**
     * Gets the value of the a4 property.
     * 
     * @return
     *     possible object is
     *     {@link A4 }
     *     
     */
    public A4 getA4() {
        return a4;
    }

    /**
     * Sets the value of the a4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link A4 }
     *     
     */
    public void setA4(A4 value) {
        this.a4 = value;
    }

    /**
     * Gets the value of the a5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA5() {
        return a5;
    }

    /**
     * Sets the value of the a5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA5(String value) {
        this.a5 = value;
    }

    /**
     * Gets the value of the a6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA6() {
        return a6;
    }

    /**
     * Sets the value of the a6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA6(String value) {
        this.a6 = value;
    }

    /**
     * Gets the value of the a7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA7() {
        return a7;
    }

    /**
     * Sets the value of the a7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA7(String value) {
        this.a7 = value;
    }

    /**
     * Gets the value of the a8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA8() {
        return a8;
    }

    /**
     * Sets the value of the a8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA8(String value) {
        this.a8 = value;
    }

    /**
     * Gets the value of the a9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA9() {
        return a9;
    }

    /**
     * Sets the value of the a9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA9(String value) {
        this.a9 = value;
    }

    /**
     * Gets the value of the a10 property.
     * 
     * @return
     *     possible object is
     *     {@link A10 }
     *     
     */
    public A10 getA10() {
        return a10;
    }

    /**
     * Sets the value of the a10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link A10 }
     *     
     */
    public void setA10(A10 value) {
        this.a10 = value;
    }

    /**
     * Gets the value of the a11 property.
     * 
     * @return
     *     possible object is
     *     {@link A11 }
     *     
     */
    public A11 getA11() {
        return a11;
    }

    /**
     * Sets the value of the a11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link A11 }
     *     
     */
    public void setA11(A11 value) {
        this.a11 = value;
    }

    /**
     * Gets the value of the a12 property.
     * 
     * @return
     *     possible object is
     *     {@link A12 }
     *     
     */
    public A12 getA12() {
        return a12;
    }

    /**
     * Sets the value of the a12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link A12 }
     *     
     */
    public void setA12(A12 value) {
        this.a12 = value;
    }

    /**
     * Gets the value of the a13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA13() {
        return a13;
    }

    /**
     * Sets the value of the a13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA13(String value) {
        this.a13 = value;
    }

    /**
     * Gets the value of the a14 property.
     * 
     * @return
     *     possible object is
     *     {@link A14 }
     *     
     */
    public A14 getA14() {
        return a14;
    }

    /**
     * Sets the value of the a14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link A14 }
     *     
     */
    public void setA14(A14 value) {
        this.a14 = value;
    }

    /**
     * Gets the value of the a15 property.
     * 
     * @return
     *     possible object is
     *     {@link A15 }
     *     
     */
    public A15 getA15() {
        return a15;
    }

    /**
     * Sets the value of the a15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link A15 }
     *     
     */
    public void setA15(A15 value) {
        this.a15 = value;
    }

    /**
     * Gets the value of the a16 property.
     * 
     * @return
     *     possible object is
     *     {@link A16 }
     *     
     */
    public A16 getA16() {
        return a16;
    }

    /**
     * Sets the value of the a16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link A16 }
     *     
     */
    public void setA16(A16 value) {
        this.a16 = value;
    }

}
