//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.04 at 05:41:36 PM CLST 
//


package bbr.b2b.regional.logistic.parser.dte;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bbr.b2b.regional.logistic.parser.dte package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Signature_QNAME = new QName("", "Signature", "");
    private final static QName _DTE_QNAME = new QName("", "DTE", "");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bbr.b2b.regional.logistic.parser.dte
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo }
     * 
     */
    public SignatureType.KeyInfo createSignatureTypeKeyInfo() {
        return new SignatureType.KeyInfo();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.KeyValue }
     * 
     */
    public SignatureType.KeyInfo.KeyValue createSignatureTypeKeyInfoKeyValue() {
        return new SignatureType.KeyInfo.KeyValue();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo }
     * 
     */
    public SignatureType.SignedInfo createSignatureTypeSignedInfo() {
        return new SignatureType.SignedInfo();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference }
     * 
     */
    public SignatureType.SignedInfo.Reference createSignatureTypeSignedInfoReference() {
        return new SignatureType.SignedInfo.Reference();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference.Transforms }
     * 
     */
    public SignatureType.SignedInfo.Reference.Transforms createSignatureTypeSignedInfoReferenceTransforms() {
        return new SignatureType.SignedInfo.Reference.Transforms();
    }

    /**
     * Create an instance of {@link DTEDefType }
     * 
     */
    public DTEDefType createDTEDefType() {
        return new DTEDefType();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones }
     * 
     */
    public DTEDefType.Exportaciones createDTEDefTypeExportaciones() {
        return new DTEDefType.Exportaciones();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.TED }
     * 
     */
    public DTEDefType.Exportaciones.TED createDTEDefTypeExportacionesTED() {
        return new DTEDefType.Exportaciones.TED();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.TED.DD }
     * 
     */
    public DTEDefType.Exportaciones.TED.DD createDTEDefTypeExportacionesTEDDD() {
        return new DTEDefType.Exportaciones.TED.DD();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.TED.DD.CAF }
     * 
     */
    public DTEDefType.Exportaciones.TED.DD.CAF createDTEDefTypeExportacionesTEDDDCAF() {
        return new DTEDefType.Exportaciones.TED.DD.CAF();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.TED.DD.CAF.DA }
     * 
     */
    public DTEDefType.Exportaciones.TED.DD.CAF.DA createDTEDefTypeExportacionesTEDDDCAFDA() {
        return new DTEDefType.Exportaciones.TED.DD.CAF.DA();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Detalle }
     * 
     */
    public DTEDefType.Exportaciones.Detalle createDTEDefTypeExportacionesDetalle() {
        return new DTEDefType.Exportaciones.Detalle();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado createDTEDefTypeExportacionesEncabezado() {
        return new DTEDefType.Exportaciones.Encabezado();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado.Transporte }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado.Transporte createDTEDefTypeExportacionesEncabezadoTransporte() {
        return new DTEDefType.Exportaciones.Encabezado.Transporte();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado.Transporte.Aduana }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado.Transporte.Aduana createDTEDefTypeExportacionesEncabezadoTransporteAduana() {
        return new DTEDefType.Exportaciones.Encabezado.Transporte.Aduana();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado.Receptor }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado.Receptor createDTEDefTypeExportacionesEncabezadoReceptor() {
        return new DTEDefType.Exportaciones.Encabezado.Receptor();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado.IdDoc }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado.IdDoc createDTEDefTypeExportacionesEncabezadoIdDoc() {
        return new DTEDefType.Exportaciones.Encabezado.IdDoc();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion }
     * 
     */
    public DTEDefType.Liquidacion createDTEDefTypeLiquidacion() {
        return new DTEDefType.Liquidacion();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.TED }
     * 
     */
    public DTEDefType.Liquidacion.TED createDTEDefTypeLiquidacionTED() {
        return new DTEDefType.Liquidacion.TED();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.TED.DD }
     * 
     */
    public DTEDefType.Liquidacion.TED.DD createDTEDefTypeLiquidacionTEDDD() {
        return new DTEDefType.Liquidacion.TED.DD();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.TED.DD.CAF }
     * 
     */
    public DTEDefType.Liquidacion.TED.DD.CAF createDTEDefTypeLiquidacionTEDDDCAF() {
        return new DTEDefType.Liquidacion.TED.DD.CAF();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.TED.DD.CAF.DA }
     * 
     */
    public DTEDefType.Liquidacion.TED.DD.CAF.DA createDTEDefTypeLiquidacionTEDDDCAFDA() {
        return new DTEDefType.Liquidacion.TED.DD.CAF.DA();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Detalle }
     * 
     */
    public DTEDefType.Liquidacion.Detalle createDTEDefTypeLiquidacionDetalle() {
        return new DTEDefType.Liquidacion.Detalle();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Encabezado }
     * 
     */
    public DTEDefType.Liquidacion.Encabezado createDTEDefTypeLiquidacionEncabezado() {
        return new DTEDefType.Liquidacion.Encabezado();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Encabezado.Totales }
     * 
     */
    public DTEDefType.Liquidacion.Encabezado.Totales createDTEDefTypeLiquidacionEncabezadoTotales() {
        return new DTEDefType.Liquidacion.Encabezado.Totales();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Encabezado.IdDoc }
     * 
     */
    public DTEDefType.Liquidacion.Encabezado.IdDoc createDTEDefTypeLiquidacionEncabezadoIdDoc() {
        return new DTEDefType.Liquidacion.Encabezado.IdDoc();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento }
     * 
     */
    public DTEDefType.Documento createDTEDefTypeDocumento() {
        return new DTEDefType.Documento();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.TED }
     * 
     */
    public DTEDefType.Documento.TED createDTEDefTypeDocumentoTED() {
        return new DTEDefType.Documento.TED();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.TED.DD }
     * 
     */
    public DTEDefType.Documento.TED.DD createDTEDefTypeDocumentoTEDDD() {
        return new DTEDefType.Documento.TED.DD();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.TED.DD.CAF }
     * 
     */
    public DTEDefType.Documento.TED.DD.CAF createDTEDefTypeDocumentoTEDDDCAF() {
        return new DTEDefType.Documento.TED.DD.CAF();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.TED.DD.CAF.DA }
     * 
     */
    public DTEDefType.Documento.TED.DD.CAF.DA createDTEDefTypeDocumentoTEDDDCAFDA() {
        return new DTEDefType.Documento.TED.DD.CAF.DA();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Detalle }
     * 
     */
    public DTEDefType.Documento.Detalle createDTEDefTypeDocumentoDetalle() {
        return new DTEDefType.Documento.Detalle();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado }
     * 
     */
    public DTEDefType.Documento.Encabezado createDTEDefTypeDocumentoEncabezado() {
        return new DTEDefType.Documento.Encabezado();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.OtraMoneda }
     * 
     */
    public DTEDefType.Documento.Encabezado.OtraMoneda createDTEDefTypeDocumentoEncabezadoOtraMoneda() {
        return new DTEDefType.Documento.Encabezado.OtraMoneda();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.Totales }
     * 
     */
    public DTEDefType.Documento.Encabezado.Totales createDTEDefTypeDocumentoEncabezadoTotales() {
        return new DTEDefType.Documento.Encabezado.Totales();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.Transporte }
     * 
     */
    public DTEDefType.Documento.Encabezado.Transporte createDTEDefTypeDocumentoEncabezadoTransporte() {
        return new DTEDefType.Documento.Encabezado.Transporte();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.Transporte.Aduana }
     * 
     */
    public DTEDefType.Documento.Encabezado.Transporte.Aduana createDTEDefTypeDocumentoEncabezadoTransporteAduana() {
        return new DTEDefType.Documento.Encabezado.Transporte.Aduana();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.Receptor }
     * 
     */
    public DTEDefType.Documento.Encabezado.Receptor createDTEDefTypeDocumentoEncabezadoReceptor() {
        return new DTEDefType.Documento.Encabezado.Receptor();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.Emisor }
     * 
     */
    public DTEDefType.Documento.Encabezado.Emisor createDTEDefTypeDocumentoEncabezadoEmisor() {
        return new DTEDefType.Documento.Encabezado.Emisor();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.IdDoc }
     * 
     */
    public DTEDefType.Documento.Encabezado.IdDoc createDTEDefTypeDocumentoEncabezadoIdDoc() {
        return new DTEDefType.Documento.Encabezado.IdDoc();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.X509Data }
     * 
     */
    public SignatureType.KeyInfo.X509Data createSignatureTypeKeyInfoX509Data() {
        return new SignatureType.KeyInfo.X509Data();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.KeyValue.RSAKeyValue }
     * 
     */
    public SignatureType.KeyInfo.KeyValue.RSAKeyValue createSignatureTypeKeyInfoKeyValueRSAKeyValue() {
        return new SignatureType.KeyInfo.KeyValue.RSAKeyValue();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.KeyValue.DSAKeyValue }
     * 
     */
    public SignatureType.KeyInfo.KeyValue.DSAKeyValue createSignatureTypeKeyInfoKeyValueDSAKeyValue() {
        return new SignatureType.KeyInfo.KeyValue.DSAKeyValue();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.CanonicalizationMethod }
     * 
     */
    public SignatureType.SignedInfo.CanonicalizationMethod createSignatureTypeSignedInfoCanonicalizationMethod() {
        return new SignatureType.SignedInfo.CanonicalizationMethod();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.SignatureMethod }
     * 
     */
    public SignatureType.SignedInfo.SignatureMethod createSignatureTypeSignedInfoSignatureMethod() {
        return new SignatureType.SignedInfo.SignatureMethod();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference.DigestMethod }
     * 
     */
    public SignatureType.SignedInfo.Reference.DigestMethod createSignatureTypeSignedInfoReferenceDigestMethod() {
        return new SignatureType.SignedInfo.Reference.DigestMethod();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference.Transforms.Transform }
     * 
     */
    public SignatureType.SignedInfo.Reference.Transforms.Transform createSignatureTypeSignedInfoReferenceTransformsTransform() {
        return new SignatureType.SignedInfo.Reference.Transforms.Transform();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.SubTotInfo }
     * 
     */
    public DTEDefType.Exportaciones.SubTotInfo createDTEDefTypeExportacionesSubTotInfo() {
        return new DTEDefType.Exportaciones.SubTotInfo();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.DscRcgGlobal }
     * 
     */
    public DTEDefType.Exportaciones.DscRcgGlobal createDTEDefTypeExportacionesDscRcgGlobal() {
        return new DTEDefType.Exportaciones.DscRcgGlobal();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Referencia }
     * 
     */
    public DTEDefType.Exportaciones.Referencia createDTEDefTypeExportacionesReferencia() {
        return new DTEDefType.Exportaciones.Referencia();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.TED.FRMT }
     * 
     */
    public DTEDefType.Exportaciones.TED.FRMT createDTEDefTypeExportacionesTEDFRMT() {
        return new DTEDefType.Exportaciones.TED.FRMT();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.TED.DD.CAF.FRMA }
     * 
     */
    public DTEDefType.Exportaciones.TED.DD.CAF.FRMA createDTEDefTypeExportacionesTEDDDCAFFRMA() {
        return new DTEDefType.Exportaciones.TED.DD.CAF.FRMA();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.TED.DD.CAF.DA.RNG }
     * 
     */
    public DTEDefType.Exportaciones.TED.DD.CAF.DA.RNG createDTEDefTypeExportacionesTEDDDCAFDARNG() {
        return new DTEDefType.Exportaciones.TED.DD.CAF.DA.RNG();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.TED.DD.CAF.DA.RSAPK }
     * 
     */
    public DTEDefType.Exportaciones.TED.DD.CAF.DA.RSAPK createDTEDefTypeExportacionesTEDDDCAFDARSAPK() {
        return new DTEDefType.Exportaciones.TED.DD.CAF.DA.RSAPK();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.TED.DD.CAF.DA.DSAPK }
     * 
     */
    public DTEDefType.Exportaciones.TED.DD.CAF.DA.DSAPK createDTEDefTypeExportacionesTEDDDCAFDADSAPK() {
        return new DTEDefType.Exportaciones.TED.DD.CAF.DA.DSAPK();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Detalle.CdgItem }
     * 
     */
    public DTEDefType.Exportaciones.Detalle.CdgItem createDTEDefTypeExportacionesDetalleCdgItem() {
        return new DTEDefType.Exportaciones.Detalle.CdgItem();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Detalle.Subcantidad }
     * 
     */
    public DTEDefType.Exportaciones.Detalle.Subcantidad createDTEDefTypeExportacionesDetalleSubcantidad() {
        return new DTEDefType.Exportaciones.Detalle.Subcantidad();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Detalle.OtrMnda }
     * 
     */
    public DTEDefType.Exportaciones.Detalle.OtrMnda createDTEDefTypeExportacionesDetalleOtrMnda() {
        return new DTEDefType.Exportaciones.Detalle.OtrMnda();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Detalle.SubDscto }
     * 
     */
    public DTEDefType.Exportaciones.Detalle.SubDscto createDTEDefTypeExportacionesDetalleSubDscto() {
        return new DTEDefType.Exportaciones.Detalle.SubDscto();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Detalle.SubRecargo }
     * 
     */
    public DTEDefType.Exportaciones.Detalle.SubRecargo createDTEDefTypeExportacionesDetalleSubRecargo() {
        return new DTEDefType.Exportaciones.Detalle.SubRecargo();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado.Emisor }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado.Emisor createDTEDefTypeExportacionesEncabezadoEmisor() {
        return new DTEDefType.Exportaciones.Encabezado.Emisor();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado.Totales }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado.Totales createDTEDefTypeExportacionesEncabezadoTotales() {
        return new DTEDefType.Exportaciones.Encabezado.Totales();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado.OtraMoneda }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado.OtraMoneda createDTEDefTypeExportacionesEncabezadoOtraMoneda() {
        return new DTEDefType.Exportaciones.Encabezado.OtraMoneda();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado.Transporte.Chofer }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado.Transporte.Chofer createDTEDefTypeExportacionesEncabezadoTransporteChofer() {
        return new DTEDefType.Exportaciones.Encabezado.Transporte.Chofer();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado.Transporte.Aduana.TipoBultos }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado.Transporte.Aduana.TipoBultos createDTEDefTypeExportacionesEncabezadoTransporteAduanaTipoBultos() {
        return new DTEDefType.Exportaciones.Encabezado.Transporte.Aduana.TipoBultos();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado.Receptor.Extranjero }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado.Receptor.Extranjero createDTEDefTypeExportacionesEncabezadoReceptorExtranjero() {
        return new DTEDefType.Exportaciones.Encabezado.Receptor.Extranjero();
    }

    /**
     * Create an instance of {@link DTEDefType.Exportaciones.Encabezado.IdDoc.MntPagos }
     * 
     */
    public DTEDefType.Exportaciones.Encabezado.IdDoc.MntPagos createDTEDefTypeExportacionesEncabezadoIdDocMntPagos() {
        return new DTEDefType.Exportaciones.Encabezado.IdDoc.MntPagos();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.SubTotInfo }
     * 
     */
    public DTEDefType.Liquidacion.SubTotInfo createDTEDefTypeLiquidacionSubTotInfo() {
        return new DTEDefType.Liquidacion.SubTotInfo();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Referencia }
     * 
     */
    public DTEDefType.Liquidacion.Referencia createDTEDefTypeLiquidacionReferencia() {
        return new DTEDefType.Liquidacion.Referencia();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Comisiones }
     * 
     */
    public DTEDefType.Liquidacion.Comisiones createDTEDefTypeLiquidacionComisiones() {
        return new DTEDefType.Liquidacion.Comisiones();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.TED.FRMT }
     * 
     */
    public DTEDefType.Liquidacion.TED.FRMT createDTEDefTypeLiquidacionTEDFRMT() {
        return new DTEDefType.Liquidacion.TED.FRMT();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.TED.DD.CAF.FRMA }
     * 
     */
    public DTEDefType.Liquidacion.TED.DD.CAF.FRMA createDTEDefTypeLiquidacionTEDDDCAFFRMA() {
        return new DTEDefType.Liquidacion.TED.DD.CAF.FRMA();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.TED.DD.CAF.DA.RNG }
     * 
     */
    public DTEDefType.Liquidacion.TED.DD.CAF.DA.RNG createDTEDefTypeLiquidacionTEDDDCAFDARNG() {
        return new DTEDefType.Liquidacion.TED.DD.CAF.DA.RNG();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.TED.DD.CAF.DA.RSAPK }
     * 
     */
    public DTEDefType.Liquidacion.TED.DD.CAF.DA.RSAPK createDTEDefTypeLiquidacionTEDDDCAFDARSAPK() {
        return new DTEDefType.Liquidacion.TED.DD.CAF.DA.RSAPK();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.TED.DD.CAF.DA.DSAPK }
     * 
     */
    public DTEDefType.Liquidacion.TED.DD.CAF.DA.DSAPK createDTEDefTypeLiquidacionTEDDDCAFDADSAPK() {
        return new DTEDefType.Liquidacion.TED.DD.CAF.DA.DSAPK();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Detalle.CdgItem }
     * 
     */
    public DTEDefType.Liquidacion.Detalle.CdgItem createDTEDefTypeLiquidacionDetalleCdgItem() {
        return new DTEDefType.Liquidacion.Detalle.CdgItem();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Detalle.Subcantidad }
     * 
     */
    public DTEDefType.Liquidacion.Detalle.Subcantidad createDTEDefTypeLiquidacionDetalleSubcantidad() {
        return new DTEDefType.Liquidacion.Detalle.Subcantidad();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Encabezado.Emisor }
     * 
     */
    public DTEDefType.Liquidacion.Encabezado.Emisor createDTEDefTypeLiquidacionEncabezadoEmisor() {
        return new DTEDefType.Liquidacion.Encabezado.Emisor();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Encabezado.Receptor }
     * 
     */
    public DTEDefType.Liquidacion.Encabezado.Receptor createDTEDefTypeLiquidacionEncabezadoReceptor() {
        return new DTEDefType.Liquidacion.Encabezado.Receptor();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Encabezado.Totales.ImptoReten }
     * 
     */
    public DTEDefType.Liquidacion.Encabezado.Totales.ImptoReten createDTEDefTypeLiquidacionEncabezadoTotalesImptoReten() {
        return new DTEDefType.Liquidacion.Encabezado.Totales.ImptoReten();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Encabezado.Totales.Comisiones }
     * 
     */
    public DTEDefType.Liquidacion.Encabezado.Totales.Comisiones createDTEDefTypeLiquidacionEncabezadoTotalesComisiones() {
        return new DTEDefType.Liquidacion.Encabezado.Totales.Comisiones();
    }

    /**
     * Create an instance of {@link DTEDefType.Liquidacion.Encabezado.IdDoc.MntPagos }
     * 
     */
    public DTEDefType.Liquidacion.Encabezado.IdDoc.MntPagos createDTEDefTypeLiquidacionEncabezadoIdDocMntPagos() {
        return new DTEDefType.Liquidacion.Encabezado.IdDoc.MntPagos();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.SubTotInfo }
     * 
     */
    public DTEDefType.Documento.SubTotInfo createDTEDefTypeDocumentoSubTotInfo() {
        return new DTEDefType.Documento.SubTotInfo();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.DscRcgGlobal }
     * 
     */
    public DTEDefType.Documento.DscRcgGlobal createDTEDefTypeDocumentoDscRcgGlobal() {
        return new DTEDefType.Documento.DscRcgGlobal();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Referencia }
     * 
     */
    public DTEDefType.Documento.Referencia createDTEDefTypeDocumentoReferencia() {
        return new DTEDefType.Documento.Referencia();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Comisiones }
     * 
     */
    public DTEDefType.Documento.Comisiones createDTEDefTypeDocumentoComisiones() {
        return new DTEDefType.Documento.Comisiones();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.TED.FRMT }
     * 
     */
    public DTEDefType.Documento.TED.FRMT createDTEDefTypeDocumentoTEDFRMT() {
        return new DTEDefType.Documento.TED.FRMT();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.TED.DD.CAF.FRMA }
     * 
     */
    public DTEDefType.Documento.TED.DD.CAF.FRMA createDTEDefTypeDocumentoTEDDDCAFFRMA() {
        return new DTEDefType.Documento.TED.DD.CAF.FRMA();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.TED.DD.CAF.DA.RNG }
     * 
     */
    public DTEDefType.Documento.TED.DD.CAF.DA.RNG createDTEDefTypeDocumentoTEDDDCAFDARNG() {
        return new DTEDefType.Documento.TED.DD.CAF.DA.RNG();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.TED.DD.CAF.DA.RSAPK }
     * 
     */
    public DTEDefType.Documento.TED.DD.CAF.DA.RSAPK createDTEDefTypeDocumentoTEDDDCAFDARSAPK() {
        return new DTEDefType.Documento.TED.DD.CAF.DA.RSAPK();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.TED.DD.CAF.DA.DSAPK }
     * 
     */
    public DTEDefType.Documento.TED.DD.CAF.DA.DSAPK createDTEDefTypeDocumentoTEDDDCAFDADSAPK() {
        return new DTEDefType.Documento.TED.DD.CAF.DA.DSAPK();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Detalle.CdgItem }
     * 
     */
    public DTEDefType.Documento.Detalle.CdgItem createDTEDefTypeDocumentoDetalleCdgItem() {
        return new DTEDefType.Documento.Detalle.CdgItem();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Detalle.Retenedor }
     * 
     */
    public DTEDefType.Documento.Detalle.Retenedor createDTEDefTypeDocumentoDetalleRetenedor() {
        return new DTEDefType.Documento.Detalle.Retenedor();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Detalle.Subcantidad }
     * 
     */
    public DTEDefType.Documento.Detalle.Subcantidad createDTEDefTypeDocumentoDetalleSubcantidad() {
        return new DTEDefType.Documento.Detalle.Subcantidad();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Detalle.OtrMnda }
     * 
     */
    public DTEDefType.Documento.Detalle.OtrMnda createDTEDefTypeDocumentoDetalleOtrMnda() {
        return new DTEDefType.Documento.Detalle.OtrMnda();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Detalle.SubDscto }
     * 
     */
    public DTEDefType.Documento.Detalle.SubDscto createDTEDefTypeDocumentoDetalleSubDscto() {
        return new DTEDefType.Documento.Detalle.SubDscto();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Detalle.SubRecargo }
     * 
     */
    public DTEDefType.Documento.Detalle.SubRecargo createDTEDefTypeDocumentoDetalleSubRecargo() {
        return new DTEDefType.Documento.Detalle.SubRecargo();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.OtraMoneda.ImpRetOtrMnda }
     * 
     */
    public DTEDefType.Documento.Encabezado.OtraMoneda.ImpRetOtrMnda createDTEDefTypeDocumentoEncabezadoOtraMonedaImpRetOtrMnda() {
        return new DTEDefType.Documento.Encabezado.OtraMoneda.ImpRetOtrMnda();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.Totales.ImptoReten }
     * 
     */
    public DTEDefType.Documento.Encabezado.Totales.ImptoReten createDTEDefTypeDocumentoEncabezadoTotalesImptoReten() {
        return new DTEDefType.Documento.Encabezado.Totales.ImptoReten();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.Totales.Comisiones }
     * 
     */
    public DTEDefType.Documento.Encabezado.Totales.Comisiones createDTEDefTypeDocumentoEncabezadoTotalesComisiones() {
        return new DTEDefType.Documento.Encabezado.Totales.Comisiones();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.Transporte.Chofer }
     * 
     */
    public DTEDefType.Documento.Encabezado.Transporte.Chofer createDTEDefTypeDocumentoEncabezadoTransporteChofer() {
        return new DTEDefType.Documento.Encabezado.Transporte.Chofer();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.Transporte.Aduana.TipoBultos }
     * 
     */
    public DTEDefType.Documento.Encabezado.Transporte.Aduana.TipoBultos createDTEDefTypeDocumentoEncabezadoTransporteAduanaTipoBultos() {
        return new DTEDefType.Documento.Encabezado.Transporte.Aduana.TipoBultos();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.Receptor.Extranjero }
     * 
     */
    public DTEDefType.Documento.Encabezado.Receptor.Extranjero createDTEDefTypeDocumentoEncabezadoReceptorExtranjero() {
        return new DTEDefType.Documento.Encabezado.Receptor.Extranjero();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.Emisor.GuiaExport }
     * 
     */
    public DTEDefType.Documento.Encabezado.Emisor.GuiaExport createDTEDefTypeDocumentoEncabezadoEmisorGuiaExport() {
        return new DTEDefType.Documento.Encabezado.Emisor.GuiaExport();
    }

    /**
     * Create an instance of {@link DTEDefType.Documento.Encabezado.IdDoc.MntPagos }
     * 
     */
    public DTEDefType.Documento.Encabezado.IdDoc.MntPagos createDTEDefTypeDocumentoEncabezadoIdDocMntPagos() {
        return new DTEDefType.Documento.Encabezado.IdDoc.MntPagos();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Signature")
    public JAXBElement<SignatureType> createSignature(SignatureType value) {
        return new JAXBElement<SignatureType>(_Signature_QNAME, SignatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DTEDefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DTE")
    public JAXBElement<DTEDefType> createDTE(DTEDefType value) {
        return new JAXBElement<DTEDefType>(_DTE_QNAME, DTEDefType.class, null, value);
    }

}
