//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.10 at 11:10:58 AM CLT 
//


package bbr.b2b.regional.logistic.parser.pldownload;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="detalle">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="delivery" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="palletid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="bulkid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tipoflujo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="codlocal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="local" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="departamento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="numdoctributario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="numorden" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="codigoproveedor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nombreproducto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cantidad" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "detalle"
})
@XmlRootElement(name = "PackingList")
public class PackingList {

    @XmlElement(required = true)
    protected List<PackingList.Detalle> detalle;

    /**
     * Gets the value of the detalle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detalle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetalle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackingList.Detalle }
     * 
     * 
     */
    public List<PackingList.Detalle> getDetalle() {
        if (detalle == null) {
            detalle = new ArrayList<PackingList.Detalle>();
        }
        return this.detalle;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="delivery" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="palletid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="bulkid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tipoflujo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="codlocal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="local" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="departamento" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="numdoctributario" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="numorden" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="codigoproveedor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="nombreproducto" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cantidad" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "delivery",
        "palletid",
        "bulkid",
        "tipoflujo",
        "codlocal",
        "local",
        "departamento",
        "numdoctributario",
        "numorden",
        "sku",
        "codigoproveedor",
        "nombreproducto",
        "cantidad"
    })
    public static class Detalle {

        protected long delivery;
        @XmlElement(required = true)
        protected String palletid;
        @XmlElement(required = true)
        protected String bulkid;
        @XmlElement(required = true)
        protected String tipoflujo;
        @XmlElement(required = true)
        protected String codlocal;
        @XmlElement(required = true)
        protected String local;
        @XmlElement(required = true)
        protected String departamento;
        @XmlElement(required = true)
        protected String numdoctributario;
        @XmlElement(required = true)
        protected String numorden;
        @XmlElement(required = true)
        protected String sku;
        @XmlElement(required = true)
        protected String codigoproveedor;
        @XmlElement(required = true)
        protected String nombreproducto;
        protected int cantidad;

        /**
         * Gets the value of the delivery property.
         * 
         */
        public long getDelivery() {
            return delivery;
        }

        /**
         * Sets the value of the delivery property.
         * 
         */
        public void setDelivery(long value) {
            this.delivery = value;
        }

        /**
         * Gets the value of the palletid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPalletid() {
            return palletid;
        }

        /**
         * Sets the value of the palletid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPalletid(String value) {
            this.palletid = value;
        }

        /**
         * Gets the value of the bulkid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBulkid() {
            return bulkid;
        }

        /**
         * Sets the value of the bulkid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBulkid(String value) {
            this.bulkid = value;
        }

        /**
         * Gets the value of the tipoflujo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoflujo() {
            return tipoflujo;
        }

        /**
         * Sets the value of the tipoflujo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoflujo(String value) {
            this.tipoflujo = value;
        }

        /**
         * Gets the value of the codlocal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodlocal() {
            return codlocal;
        }

        /**
         * Sets the value of the codlocal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodlocal(String value) {
            this.codlocal = value;
        }

        /**
         * Gets the value of the local property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocal() {
            return local;
        }

        /**
         * Sets the value of the local property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocal(String value) {
            this.local = value;
        }

        /**
         * Gets the value of the departamento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepartamento() {
            return departamento;
        }

        /**
         * Sets the value of the departamento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepartamento(String value) {
            this.departamento = value;
        }

        /**
         * Gets the value of the numdoctributario property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumdoctributario() {
            return numdoctributario;
        }

        /**
         * Sets the value of the numdoctributario property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumdoctributario(String value) {
            this.numdoctributario = value;
        }

        /**
         * Gets the value of the numorden property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumorden() {
            return numorden;
        }

        /**
         * Sets the value of the numorden property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumorden(String value) {
            this.numorden = value;
        }

        /**
         * Gets the value of the sku property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSku() {
            return sku;
        }

        /**
         * Sets the value of the sku property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSku(String value) {
            this.sku = value;
        }

        /**
         * Gets the value of the codigoproveedor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigoproveedor() {
            return codigoproveedor;
        }

        /**
         * Sets the value of the codigoproveedor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodigoproveedor(String value) {
            this.codigoproveedor = value;
        }

        /**
         * Gets the value of the nombreproducto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombreproducto() {
            return nombreproducto;
        }

        /**
         * Sets the value of the nombreproducto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombreproducto(String value) {
            this.nombreproducto = value;
        }

        /**
         * Gets the value of the cantidad property.
         * 
         */
        public int getCantidad() {
            return cantidad;
        }

        /**
         * Sets the value of the cantidad property.
         * 
         */
        public void setCantidad(int value) {
            this.cantidad = value;
        }

    }

}
