//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.04 at 10:31:23 AM CLT 
//


package bbr.b2b.regional.logistic.xml.qreception;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bbr.b2b.regional.logistic.xml.qreception package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Secuencia_QNAME = new QName("", "secuencia");
    private final static QName _Cantidad_QNAME = new QName("", "cantidad");
    private final static QName _Norden_QNAME = new QName("", "norden");
    private final static QName _Nrecepcion_QNAME = new QName("", "nrecepcion");
    private final static QName _Codloc_QNAME = new QName("", "codloc");
    private final static QName _Warehouse_QNAME = new QName("", "warehouse");
    private final static QName _Nasn_QNAME = new QName("", "nasn");
    private final static QName _CodProducto_QNAME = new QName("", "cod_producto");
    private final static QName _FRecepcion_QNAME = new QName("", "f_recepcion");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bbr.b2b.regional.logistic.xml.qreception
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QRECEPCION }
     * 
     */
    public QRECEPCION createQRECEPCION() {
        return new QRECEPCION();
    }

    /**
     * Create an instance of {@link Detalles }
     * 
     */
    public Detalles createDetalles() {
        return new Detalles();
    }

    /**
     * Create an instance of {@link Detalle }
     * 
     */
    public Detalle createDetalle() {
        return new Detalle();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "secuencia")
    public JAXBElement<Long> createSecuencia(Long value) {
        return new JAXBElement<Long>(_Secuencia_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cantidad")
    public JAXBElement<Double> createCantidad(Double value) {
        return new JAXBElement<Double>(_Cantidad_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "norden")
    public JAXBElement<Long> createNorden(Long value) {
        return new JAXBElement<Long>(_Norden_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nrecepcion")
    public JAXBElement<Long> createNrecepcion(Long value) {
        return new JAXBElement<Long>(_Nrecepcion_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "codloc")
    public JAXBElement<String> createCodloc(String value) {
        return new JAXBElement<String>(_Codloc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "warehouse")
    public JAXBElement<String> createWarehouse(String value) {
        return new JAXBElement<String>(_Warehouse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nasn")
    public JAXBElement<Long> createNasn(Long value) {
        return new JAXBElement<Long>(_Nasn_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cod_producto")
    public JAXBElement<String> createCodProducto(String value) {
        return new JAXBElement<String>(_CodProducto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "f_recepcion")
    public JAXBElement<String> createFRecepcion(String value) {
        return new JAXBElement<String>(_FRecepcion_QNAME, String.class, null, value);
    }

}
