//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.06 at 04:39:10 PM CLST 
//


package bbr.b2b.regional.logistic.xml.int1874;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}cod_destino"/>
 *         &lt;element ref="{}tiempo_entrega"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codDestino",
    "tiempoEntrega"
})
@XmlRootElement(name = "entrega_destino")
public class EntregaDestino {

    @XmlElement(name = "cod_destino")
    protected int codDestino;
    @XmlElement(name = "tiempo_entrega")
    protected int tiempoEntrega;

    /**
     * Gets the value of the codDestino property.
     * 
     */
    public int getCodDestino() {
        return codDestino;
    }

    /**
     * Sets the value of the codDestino property.
     * 
     */
    public void setCodDestino(int value) {
        this.codDestino = value;
    }

    /**
     * Gets the value of the tiempoEntrega property.
     * 
     */
    public int getTiempoEntrega() {
        return tiempoEntrega;
    }

    /**
     * Sets the value of the tiempoEntrega property.
     * 
     */
    public void setTiempoEntrega(int value) {
        this.tiempoEntrega = value;
    }

}
