//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 12:53:25 PM CLT 
//


package bbr.b2b.regional.logistic.parser.pl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="detalle">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="no_orden" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="cod_local" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cod_prod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="no_bulto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="no_pallet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cantidad" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="no_doc_tributario" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "detalle"
})
@XmlRootElement(name = "PL")
public class PL {

    @XmlElement(required = true)
    protected List<PL.Detalle> detalle;

    /**
     * Gets the value of the detalle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detalle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetalle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PL.Detalle }
     * 
     * 
     */
    public List<PL.Detalle> getDetalle() {
        if (detalle == null) {
            detalle = new ArrayList<PL.Detalle>();
        }
        return this.detalle;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="no_orden" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="cod_local" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cod_prod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="no_bulto" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="no_pallet" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cantidad" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="no_doc_tributario" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "noOrden",
        "codLocal",
        "codProd",
        "noBulto",
        "noPallet",
        "cantidad",
        "noDocTributario"
    })
    public static class Detalle {

        @XmlElement(name = "no_orden")
        protected int noOrden;
        @XmlElement(name = "cod_local", required = true)
        protected String codLocal;
        @XmlElement(name = "cod_prod", required = true)
        protected String codProd;
        @XmlElement(name = "no_bulto", required = true)
        protected String noBulto;
        @XmlElement(name = "no_pallet", required = true)
        protected String noPallet;
        protected float cantidad;
        @XmlElement(name = "no_doc_tributario")
        protected long noDocTributario;

        /**
         * Gets the value of the noOrden property.
         * 
         */
        public int getNoOrden() {
            return noOrden;
        }

        /**
         * Sets the value of the noOrden property.
         * 
         */
        public void setNoOrden(int value) {
            this.noOrden = value;
        }

        /**
         * Gets the value of the codLocal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodLocal() {
            return codLocal;
        }

        /**
         * Sets the value of the codLocal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodLocal(String value) {
            this.codLocal = value;
        }

        /**
         * Gets the value of the codProd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodProd() {
            return codProd;
        }

        /**
         * Sets the value of the codProd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodProd(String value) {
            this.codProd = value;
        }

        /**
         * Gets the value of the noBulto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNoBulto() {
            return noBulto;
        }

        /**
         * Sets the value of the noBulto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNoBulto(String value) {
            this.noBulto = value;
        }

        /**
         * Gets the value of the noPallet property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNoPallet() {
            return noPallet;
        }

        /**
         * Sets the value of the noPallet property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNoPallet(String value) {
            this.noPallet = value;
        }

        /**
         * Gets the value of the cantidad property.
         * 
         */
        public float getCantidad() {
            return cantidad;
        }

        /**
         * Sets the value of the cantidad property.
         * 
         */
        public void setCantidad(float value) {
            this.cantidad = value;
        }

        /**
         * Gets the value of the noDocTributario property.
         * 
         */
        public long getNoDocTributario() {
            return noDocTributario;
        }

        /**
         * Sets the value of the noDocTributario property.
         * 
         */
        public void setNoDocTributario(long value) {
            this.noDocTributario = value;
        }

    }

}
