
package bbr.esb.services.webservices.facade;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Sep 02 16:24:18 GMT-04:00 2019
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "AccessDeniedException", targetNamespace = "http://facade.webservices.services.esb.bbr/")
public class AccessDeniedException_Exception extends Exception {
    public static final long serialVersionUID = 20190902162418L;
    
    private bbr.esb.services.webservices.facade.AccessDeniedException accessDeniedException;

    public AccessDeniedException_Exception() {
        super();
    }
    
    public AccessDeniedException_Exception(String message) {
        super(message);
    }
    
    public AccessDeniedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AccessDeniedException_Exception(String message, bbr.esb.services.webservices.facade.AccessDeniedException accessDeniedException) {
        super(message);
        this.accessDeniedException = accessDeniedException;
    }

    public AccessDeniedException_Exception(String message, bbr.esb.services.webservices.facade.AccessDeniedException accessDeniedException, Throwable cause) {
        super(message, cause);
        this.accessDeniedException = accessDeniedException;
    }

    public bbr.esb.services.webservices.facade.AccessDeniedException getFaultInfo() {
        return this.accessDeniedException;
    }
}
