
/*
 * 
 */

package bbr.esb.services.webservices.facade;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Sep 02 16:24:18 GMT-04:00 2019
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "ServiceManagerServerService", 
                  wsdlLocation = "http://10.200.3.99:8180/SOA_GENERAL_Web/ServiceManagerServer?wsdl",
                  targetNamespace = "http://facade.webservices.services.esb.bbr/") 
public class ServiceManagerServerService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://facade.webservices.services.esb.bbr/", "ServiceManagerServerService");
    public final static QName ServiceManagerServerPort = new QName("http://facade.webservices.services.esb.bbr/", "ServiceManagerServerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.200.3.99:8180/SOA_GENERAL_Web/ServiceManagerServer?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://10.200.3.99:8180/SOA_GENERAL_Web/ServiceManagerServer?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ServiceManagerServerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceManagerServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceManagerServerService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ServiceManagerServer
     */
    @WebEndpoint(name = "ServiceManagerServerPort")
    public ServiceManagerServer getServiceManagerServerPort() {
        return super.getPort(ServiceManagerServerPort, ServiceManagerServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceManagerServer
     */
    @WebEndpoint(name = "ServiceManagerServerPort")
    public ServiceManagerServer getServiceManagerServerPort(WebServiceFeature... features) {
        return super.getPort(ServiceManagerServerPort, ServiceManagerServer.class, features);
    }

}
