package bbr.esb.services.webservices.facade;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Sep 02 16:24:18 GMT-04:00 2019
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://facade.webservices.services.esb.bbr/", name = "ServiceManagerServer")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceManagerServer {

    @WebMethod
    @RequestWrapper(localName = "getMessageFolder", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetMessageFolder")
    @ResponseWrapper(localName = "getMessageFolderResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetMessageFolderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public bbr.esb.services.webservices.facade.MessageFolderDataDTO getMessageFolder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getUninformedFileEvents", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetUninformedFileEvents")
    @ResponseWrapper(localName = "getUninformedFileEventsResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetUninformedFileEventsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<bbr.esb.services.webservices.facade.FileEventDataDTO> getUninformedFileEvents() throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateContractedServiceMonitorData", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.UpdateContractedServiceMonitorData")
    @ResponseWrapper(localName = "updateContractedServiceMonitorDataResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.UpdateContractedServiceMonitorDataResponse")
    public void updateContractedServiceMonitorData(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<bbr.esb.services.webservices.facade.ContractedServiceMonitorDataDTO> arg0
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doLogonUser", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoLogonUser")
    @ResponseWrapper(localName = "doLogonUserResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoLogonUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public bbr.esb.services.webservices.facade.LogonResultDTO doLogonUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "doAddServiceEvent", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoAddServiceEvent")
    @ResponseWrapper(localName = "doAddServiceEventResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoAddServiceEventResponse")
    @WebResult(name = "return", targetNamespace = "")
    public bbr.esb.services.webservices.facade.ServiceEventDTO doAddServiceEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doAddTicketEventStatus", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoAddTicketEventStatus")
    @ResponseWrapper(localName = "doAddTicketEventStatusResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoAddTicketEventStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public bbr.esb.services.webservices.facade.TicketEventDTO doAddTicketEventStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.util.List<bbr.esb.services.webservices.facade.TicketEventStatusDataDTO> arg5
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getUnprocessedServiceEvents", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetUnprocessedServiceEvents")
    @ResponseWrapper(localName = "getUnprocessedServiceEventsResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetUnprocessedServiceEventsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<bbr.esb.services.webservices.facade.ServiceEventDataDTO> getUnprocessedServiceEvents() throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doAddFileEvent", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoAddFileEvent")
    @ResponseWrapper(localName = "doAddFileEventResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoAddFileEventResponse")
    @WebResult(name = "return", targetNamespace = "")
    public bbr.esb.services.webservices.facade.FileEventDTO doAddFileEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doAddGenericServiceEvent", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoAddGenericServiceEvent")
    @ResponseWrapper(localName = "doAddGenericServiceEventResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoAddGenericServiceEventResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<bbr.esb.services.webservices.facade.ServiceEventDTO> doAddGenericServiceEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "checkUploadStatus", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.CheckUploadStatus")
    @ResponseWrapper(localName = "checkUploadStatusResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.CheckUploadStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public bbr.esb.services.webservices.facade.TicketEventResultDTO checkUploadStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doUpdateFileEventStatusofPathandUser", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoUpdateFileEventStatusofPathandUser")
    @ResponseWrapper(localName = "doUpdateFileEventStatusofPathandUserResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoUpdateFileEventStatusofPathandUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public bbr.esb.services.webservices.facade.FileEventDTO doUpdateFileEventStatusofPathandUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCredentialsBySiteService", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetCredentialsBySiteService")
    @ResponseWrapper(localName = "getCredentialsBySiteServiceResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetCredentialsBySiteServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<bbr.esb.services.webservices.facade.InitParamCSDTO> getCredentialsBySiteService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCompaniesServiceStatusReport", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetCompaniesServiceStatusReport")
    @ResponseWrapper(localName = "getCompaniesServiceStatusReportResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetCompaniesServiceStatusReportResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<bbr.esb.services.webservices.facade.CompaniesServiceStatusReportDTO> getCompaniesServiceStatusReport() throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMessageFolderofUser", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetMessageFolderofUser")
    @ResponseWrapper(localName = "getMessageFolderofUserResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetMessageFolderofUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public bbr.esb.services.webservices.facade.MessageFolderDataDTO getMessageFolderofUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMessageData", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetMessageData")
    @ResponseWrapper(localName = "getMessageDataResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetMessageDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public bbr.esb.services.webservices.facade.MessageDataDTO getMessageData(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doUpdateFileEventStatus", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoUpdateFileEventStatus")
    @ResponseWrapper(localName = "doUpdateFileEventStatusResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.DoUpdateFileEventStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public bbr.esb.services.webservices.facade.FileEventDTO doUpdateFileEventStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMessageDataofUser", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetMessageDataofUser")
    @ResponseWrapper(localName = "getMessageDataofUserResponse", targetNamespace = "http://facade.webservices.services.esb.bbr/", className = "bbr.esb.services.webservices.facade.GetMessageDataofUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public bbr.esb.services.webservices.facade.MessageDataDTO getMessageDataofUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws AccessDeniedException_Exception, OperationFailedException_Exception, NotFoundException_Exception;
}
