//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.03 at 04:42:19 PM CLT 
//


package bbr.b2b.regional.logistic.parser.label;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="etiqueta">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="numeroOrden" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="coddep" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="codbarraparis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="codsku" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="codproveedor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nombreproducto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="dimension" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="talla" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cantidad" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="precionormal" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="preciooferta" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "etiqueta"
})
@XmlRootElement(name = "cetiqueta")
public class Cetiqueta {

    @XmlElement(required = true)
    protected List<Cetiqueta.Etiqueta> etiqueta;

    /**
     * Gets the value of the etiqueta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the etiqueta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEtiqueta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cetiqueta.Etiqueta }
     * 
     * 
     */
    public List<Cetiqueta.Etiqueta> getEtiqueta() {
        if (etiqueta == null) {
            etiqueta = new ArrayList<Cetiqueta.Etiqueta>();
        }
        return this.etiqueta;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="numeroOrden" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="coddep" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="codbarraparis" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="codsku" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="codproveedor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="nombreproducto" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="dimension" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="talla" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cantidad" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="precionormal" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="preciooferta" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numeroOrden",
        "coddep",
        "codbarraparis",
        "codsku",
        "codproveedor",
        "nombreproducto",
        "color",
        "dimension",
        "talla",
        "cantidad",
        "precionormal",
        "preciooferta"
    })
    public static class Etiqueta {

        @XmlElement(required = true)
        protected String numeroOrden;
        @XmlElement(required = true)
        protected String coddep;
        @XmlElement(required = true)
        protected String codbarraparis;
        @XmlElement(required = true)
        protected String codsku;
        @XmlElement(required = true)
        protected String codproveedor;
        @XmlElement(required = true)
        protected String nombreproducto;
        @XmlElement(required = true)
        protected String color;
        @XmlElement(required = true)
        protected String dimension;
        @XmlElement(required = true)
        protected String talla;
        protected float cantidad;
        protected float precionormal;
        protected float preciooferta;

        /**
         * Gets the value of the numeroOrden property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumeroOrden() {
            return numeroOrden;
        }

        /**
         * Sets the value of the numeroOrden property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumeroOrden(String value) {
            this.numeroOrden = value;
        }

        /**
         * Gets the value of the coddep property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCoddep() {
            return coddep;
        }

        /**
         * Sets the value of the coddep property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCoddep(String value) {
            this.coddep = value;
        }

        /**
         * Gets the value of the codbarraparis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodbarraparis() {
            return codbarraparis;
        }

        /**
         * Sets the value of the codbarraparis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodbarraparis(String value) {
            this.codbarraparis = value;
        }

        /**
         * Gets the value of the codsku property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodsku() {
            return codsku;
        }

        /**
         * Sets the value of the codsku property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodsku(String value) {
            this.codsku = value;
        }

        /**
         * Gets the value of the codproveedor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodproveedor() {
            return codproveedor;
        }

        /**
         * Sets the value of the codproveedor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodproveedor(String value) {
            this.codproveedor = value;
        }

        /**
         * Gets the value of the nombreproducto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombreproducto() {
            return nombreproducto;
        }

        /**
         * Sets the value of the nombreproducto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombreproducto(String value) {
            this.nombreproducto = value;
        }

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColor(String value) {
            this.color = value;
        }

        /**
         * Gets the value of the dimension property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDimension() {
            return dimension;
        }

        /**
         * Sets the value of the dimension property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDimension(String value) {
            this.dimension = value;
        }

        /**
         * Gets the value of the talla property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTalla() {
            return talla;
        }

        /**
         * Sets the value of the talla property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTalla(String value) {
            this.talla = value;
        }

        /**
         * Gets the value of the cantidad property.
         * 
         */
        public float getCantidad() {
            return cantidad;
        }

        /**
         * Sets the value of the cantidad property.
         * 
         */
        public void setCantidad(float value) {
            this.cantidad = value;
        }

        /**
         * Gets the value of the precionormal property.
         * 
         */
        public float getPrecionormal() {
            return precionormal;
        }

        /**
         * Sets the value of the precionormal property.
         * 
         */
        public void setPrecionormal(float value) {
            this.precionormal = value;
        }

        /**
         * Gets the value of the preciooferta property.
         * 
         */
        public float getPreciooferta() {
            return preciooferta;
        }

        /**
         * Sets the value of the preciooferta property.
         * 
         */
        public void setPreciooferta(float value) {
            this.preciooferta = value;
        }

    }

}
