//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.08 at 10:26:28 AM CLST 
//


package bbr.b2b.regional.logistic.xml.int1849;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}origen"/>
 *         &lt;element ref="{}accion"/>
 *         &lt;element ref="{}id_referencia"/>
 *         &lt;element ref="{}tipo"/>
 *         &lt;element ref="{}id_compania"/>
 *         &lt;element ref="{}tipo_transaccion"/>
 *         &lt;element ref="{}listado_productos"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "origen",
    "accion",
    "idReferencia",
    "tipo",
    "idCompania",
    "tipoTransaccion",
    "listadoProductos"
})
@XmlRootElement(name = "Message")
public class Message {

    @XmlElement(required = true)
    protected String origen;
    @XmlElement(required = true)
    protected String accion;
    @XmlElement(name = "id_referencia", required = true)
    protected String idReferencia;
    @XmlElement(required = true)
    protected String tipo;
    @XmlElement(name = "id_compania", required = true)
    protected String idCompania;
    @XmlElement(name = "tipo_transaccion", required = true)
    protected String tipoTransaccion;
    @XmlElement(name = "listado_productos", required = true)
    protected ListadoProductos listadoProductos;

    /**
     * Gets the value of the origen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigen() {
        return origen;
    }

    /**
     * Sets the value of the origen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigen(String value) {
        this.origen = value;
    }

    /**
     * Gets the value of the accion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccion() {
        return accion;
    }

    /**
     * Sets the value of the accion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccion(String value) {
        this.accion = value;
    }

    /**
     * Gets the value of the idReferencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdReferencia() {
        return idReferencia;
    }

    /**
     * Sets the value of the idReferencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdReferencia(String value) {
        this.idReferencia = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the idCompania property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdCompania() {
        return idCompania;
    }

    /**
     * Sets the value of the idCompania property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdCompania(String value) {
        this.idCompania = value;
    }

    /**
     * Gets the value of the tipoTransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoTransaccion() {
        return tipoTransaccion;
    }

    /**
     * Sets the value of the tipoTransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoTransaccion(String value) {
        this.tipoTransaccion = value;
    }

    /**
     * Gets the value of the listadoProductos property.
     * 
     * @return
     *     possible object is
     *     {@link ListadoProductos }
     *     
     */
    public ListadoProductos getListadoProductos() {
        return listadoProductos;
    }

    /**
     * Sets the value of the listadoProductos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListadoProductos }
     *     
     */
    public void setListadoProductos(ListadoProductos value) {
        this.listadoProductos = value;
    }

}
