//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.08 at 10:26:28 AM CLST 
//


package bbr.b2b.regional.logistic.xml.int1849;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bbr.b2b.regional.logistic.xml.int1849 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IdReferencia_QNAME = new QName("", "id_referencia");
    private final static QName _Cantidad_QNAME = new QName("", "cantidad");
    private final static QName _Tipo_QNAME = new QName("", "tipo");
    private final static QName _UnidMedida_QNAME = new QName("", "unid_medida");
    private final static QName _CodProveedor_QNAME = new QName("", "cod_proveedor");
    private final static QName _IdCompania_QNAME = new QName("", "id_compania");
    private final static QName _TipoTransaccion_QNAME = new QName("", "tipo_transaccion");
    private final static QName _Accion_QNAME = new QName("", "accion");
    private final static QName _CodProducto_QNAME = new QName("", "cod_producto");
    private final static QName _TipoAjuste_QNAME = new QName("", "tipo_ajuste");
    private final static QName _Origen_QNAME = new QName("", "origen");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bbr.b2b.regional.logistic.xml.int1849
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link ListadoProductos }
     * 
     */
    public ListadoProductos createListadoProductos() {
        return new ListadoProductos();
    }

    /**
     * Create an instance of {@link Producto }
     * 
     */
    public Producto createProducto() {
        return new Producto();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id_referencia")
    public JAXBElement<String> createIdReferencia(String value) {
        return new JAXBElement<String>(_IdReferencia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cantidad")
    public JAXBElement<Integer> createCantidad(Integer value) {
        return new JAXBElement<Integer>(_Cantidad_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tipo")
    public JAXBElement<String> createTipo(String value) {
        return new JAXBElement<String>(_Tipo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unid_medida")
    public JAXBElement<String> createUnidMedida(String value) {
        return new JAXBElement<String>(_UnidMedida_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cod_proveedor")
    public JAXBElement<String> createCodProveedor(String value) {
        return new JAXBElement<String>(_CodProveedor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id_compania")
    public JAXBElement<String> createIdCompania(String value) {
        return new JAXBElement<String>(_IdCompania_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tipo_transaccion")
    public JAXBElement<String> createTipoTransaccion(String value) {
        return new JAXBElement<String>(_TipoTransaccion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "accion")
    public JAXBElement<String> createAccion(String value) {
        return new JAXBElement<String>(_Accion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cod_producto")
    public JAXBElement<String> createCodProducto(String value) {
        return new JAXBElement<String>(_CodProducto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tipo_ajuste")
    public JAXBElement<String> createTipoAjuste(String value) {
        return new JAXBElement<String>(_TipoAjuste_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "origen")
    public JAXBElement<String> createOrigen(String value) {
        return new JAXBElement<String>(_Origen_QNAME, String.class, null, value);
    }

}
