//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 09:09:27 AM CLST 
//


package bbr.b2b.regional.logistic.parser.order;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bbr.b2b.regional.logistic.parser.order package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bbr.b2b.regional.logistic.parser.order
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ordenes }
     * 
     */
    public Ordenes createOrdenes() {
        return new Ordenes();
    }

    /**
     * Create an instance of {@link Ordenes.Orden }
     * 
     */
    public Ordenes.Orden createOrdenesOrden() {
        return new Ordenes.Orden();
    }

    /**
     * Create an instance of {@link Ordenes.Orden.Detalles }
     * 
     */
    public Ordenes.Orden.Detalles createOrdenesOrdenDetalles() {
        return new Ordenes.Orden.Detalles();
    }

    /**
     * Create an instance of {@link Ordenes.Orden.Detalles.Detalle }
     * 
     */
    public Ordenes.Orden.Detalles.Detalle createOrdenesOrdenDetallesDetalle() {
        return new Ordenes.Orden.Detalles.Detalle();
    }

    /**
     * Create an instance of {@link Ordenes.Orden.Detalles.Detalle.Descuentos }
     * 
     */
    public Ordenes.Orden.Detalles.Detalle.Descuentos createOrdenesOrdenDetallesDetalleDescuentos() {
        return new Ordenes.Orden.Detalles.Detalle.Descuentos();
    }

    /**
     * Create an instance of {@link Ordenes.Orden.Detalles.Detalle.Distribucion }
     * 
     */
    public Ordenes.Orden.Detalles.Detalle.Distribucion createOrdenesOrdenDetallesDetalleDistribucion() {
        return new Ordenes.Orden.Detalles.Detalle.Distribucion();
    }

    /**
     * Create an instance of {@link Ordenes.Orden.DatosGenerales }
     * 
     */
    public Ordenes.Orden.DatosGenerales createOrdenesOrdenDatosGenerales() {
        return new Ordenes.Orden.DatosGenerales();
    }

    /**
     * Create an instance of {@link Ordenes.Orden.DatosGenerales.DescGenerales }
     * 
     */
    public Ordenes.Orden.DatosGenerales.DescGenerales createOrdenesOrdenDatosGeneralesDescGenerales() {
        return new Ordenes.Orden.DatosGenerales.DescGenerales();
    }

    /**
     * Create an instance of {@link Ordenes.Orden.Detalles.Detalle.Descuentos.Descuento }
     * 
     */
    public Ordenes.Orden.Detalles.Detalle.Descuentos.Descuento createOrdenesOrdenDetallesDetalleDescuentosDescuento() {
        return new Ordenes.Orden.Detalles.Detalle.Descuentos.Descuento();
    }

    /**
     * Create an instance of {@link Ordenes.Orden.Detalles.Detalle.Distribucion.DetDistr }
     * 
     */
    public Ordenes.Orden.Detalles.Detalle.Distribucion.DetDistr createOrdenesOrdenDetallesDetalleDistribucionDetDistr() {
        return new Ordenes.Orden.Detalles.Detalle.Distribucion.DetDistr();
    }

    /**
     * Create an instance of {@link Ordenes.Orden.DatosGenerales.DatosProveedor }
     * 
     */
    public Ordenes.Orden.DatosGenerales.DatosProveedor createOrdenesOrdenDatosGeneralesDatosProveedor() {
        return new Ordenes.Orden.DatosGenerales.DatosProveedor();
    }

    /**
     * Create an instance of {@link Ordenes.Orden.DatosGenerales.Responsable }
     * 
     */
    public Ordenes.Orden.DatosGenerales.Responsable createOrdenesOrdenDatosGeneralesResponsable() {
        return new Ordenes.Orden.DatosGenerales.Responsable();
    }

    /**
     * Create an instance of {@link Ordenes.Orden.DatosGenerales.DescGenerales.DescuentoGeneral }
     * 
     */
    public Ordenes.Orden.DatosGenerales.DescGenerales.DescuentoGeneral createOrdenesOrdenDatosGeneralesDescGeneralesDescuentoGeneral() {
        return new Ordenes.Orden.DatosGenerales.DescGenerales.DescuentoGeneral();
    }

}
