//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 11:23:28 AM CLT 
//


package bbr.b2b.regional.logistic.xml.qplimport;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bbr.b2b.regional.logistic.xml.qplimport package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GD_QNAME = new QName("", "GD");
    private final static QName _HH_QNAME = new QName("", "HH");
    private final static QName _SE_QNAME = new QName("", "SE");
    private final static QName _IM_QNAME = new QName("", "IM");
    private final static QName _UN_QNAME = new QName("", "UN");
    private final static QName _FE_QNAME = new QName("", "FE");
    private final static QName _SK_QNAME = new QName("", "SK");
    private final static QName _CA_QNAME = new QName("", "CA");
    private final static QName _NP_QNAME = new QName("", "NP");
    private final static QName _NO_QNAME = new QName("", "NO");
    private final static QName _AC_QNAME = new QName("", "AC");
    private final static QName _EM_QNAME = new QName("", "EM");
    private final static QName _CE_QNAME = new QName("", "CE");
    private final static QName _CD_QNAME = new QName("", "CD");
    private final static QName _IB_QNAME = new QName("", "IB");
    private final static QName _OC_QNAME = new QName("", "OC");
    private final static QName _CO_QNAME = new QName("", "CO");
    private final static QName _TB_QNAME = new QName("", "TB");
    private final static QName _NC_QNAME = new QName("", "NC");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bbr.b2b.regional.logistic.xml.qplimport
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BS }
     * 
     */
    public BS createBS() {
        return new BS();
    }

    /**
     * Create an instance of {@link BU }
     * 
     */
    public BU createBU() {
        return new BU();
    }

    /**
     * Create an instance of {@link PS }
     * 
     */
    public PS createPS() {
        return new PS();
    }

    /**
     * Create an instance of {@link PR }
     * 
     */
    public PR createPR() {
        return new PR();
    }

    /**
     * Create an instance of {@link SC }
     * 
     */
    public SC createSC() {
        return new SC();
    }

    /**
     * Create an instance of {@link PL }
     * 
     */
    public PL createPL() {
        return new PL();
    }

    /**
     * Create an instance of {@link QPLIMPORTADOREQ }
     * 
     */
    public QPLIMPORTADOREQ createQPLIMPORTADOREQ() {
        return new QPLIMPORTADOREQ();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GD")
    public JAXBElement<Long> createGD(Long value) {
        return new JAXBElement<Long>(_GD_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HH")
    public JAXBElement<String> createHH(String value) {
        return new JAXBElement<String>(_HH_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SE")
    public JAXBElement<Long> createSE(Long value) {
        return new JAXBElement<Long>(_SE_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IM")
    public JAXBElement<String> createIM(String value) {
        return new JAXBElement<String>(_IM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UN")
    public JAXBElement<BigInteger> createUN(BigInteger value) {
        return new JAXBElement<BigInteger>(_UN_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FE")
    public JAXBElement<String> createFE(String value) {
        return new JAXBElement<String>(_FE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SK")
    public JAXBElement<String> createSK(String value) {
        return new JAXBElement<String>(_SK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CA")
    public JAXBElement<BigInteger> createCA(BigInteger value) {
        return new JAXBElement<BigInteger>(_CA_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NP")
    public JAXBElement<BigInteger> createNP(BigInteger value) {
        return new JAXBElement<BigInteger>(_NP_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NO")
    public JAXBElement<String> createNO(String value) {
        return new JAXBElement<String>(_NO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AC")
    public JAXBElement<String> createAC(String value) {
        return new JAXBElement<String>(_AC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EM")
    public JAXBElement<String> createEM(String value) {
        return new JAXBElement<String>(_EM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CE")
    public JAXBElement<String> createCE(String value) {
        return new JAXBElement<String>(_CE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CD")
    public JAXBElement<String> createCD(String value) {
        return new JAXBElement<String>(_CD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IB")
    public JAXBElement<BigInteger> createIB(BigInteger value) {
        return new JAXBElement<BigInteger>(_IB_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OC")
    public JAXBElement<Long> createOC(Long value) {
        return new JAXBElement<Long>(_OC_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CO")
    public JAXBElement<String> createCO(String value) {
        return new JAXBElement<String>(_CO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TB")
    public JAXBElement<String> createTB(String value) {
        return new JAXBElement<String>(_TB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NC")
    public JAXBElement<String> createNC(String value) {
        return new JAXBElement<String>(_NC_QNAME, String.class, null, value);
    }

}
