//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.10 at 11:21:30 AM CLT 
//


package bbr.b2b.regional.logistic.xml.qchangeorderstate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bbr.b2b.regional.logistic.xml.qchangeorderstate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Secuencia_QNAME = new QName("", "secuencia");
    private final static QName _Norden_QNAME = new QName("", "norden");
    private final static QName _Nuevoestado_QNAME = new QName("", "nuevoestado");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bbr.b2b.regional.logistic.xml.qchangeorderstate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QCAMBIOESTADO }
     * 
     */
    public QCAMBIOESTADO createQCAMBIOESTADO() {
        return new QCAMBIOESTADO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "secuencia")
    public JAXBElement<Long> createSecuencia(Long value) {
        return new JAXBElement<Long>(_Secuencia_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "norden")
    public JAXBElement<Long> createNorden(Long value) {
        return new JAXBElement<Long>(_Norden_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nuevoestado")
    public JAXBElement<String> createNuevoestado(String value) {
        return new JAXBElement<String>(_Nuevoestado_QNAME, String.class, null, value);
    }

}
