//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.10 at 11:21:30 AM CLT 
//


package bbr.b2b.regional.logistic.xml.qchangeorderstate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}secuencia"/>
 *         &lt;element ref="{}norden"/>
 *         &lt;element ref="{}nuevoestado"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "secuencia",
    "norden",
    "nuevoestado"
})
@XmlRootElement(name = "QCAMBIOESTADO")
public class QCAMBIOESTADO {

    protected long secuencia;
    protected long norden;
    @XmlElement(required = true)
    protected String nuevoestado;

    /**
     * Gets the value of the secuencia property.
     * 
     */
    public long getSecuencia() {
        return secuencia;
    }

    /**
     * Sets the value of the secuencia property.
     * 
     */
    public void setSecuencia(long value) {
        this.secuencia = value;
    }

    /**
     * Gets the value of the norden property.
     * 
     */
    public long getNorden() {
        return norden;
    }

    /**
     * Sets the value of the norden property.
     * 
     */
    public void setNorden(long value) {
        this.norden = value;
    }

    /**
     * Gets the value of the nuevoestado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuevoestado() {
        return nuevoestado;
    }

    /**
     * Sets the value of the nuevoestado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuevoestado(String value) {
        this.nuevoestado = value;
    }

}
