package bbr.b2b.regional.logistic.evaluations.data.wrappers;

import java.util.Date;

import bbr.b2b.common.adtclasses.classes.ElementDTO;
import bbr.b2b.regional.logistic.evaluations.data.interfaces.IReceptionEvaluation;

public class ReceptionEvaluationW extends ElementDTO implements IReceptionEvaluation {

	private Boolean autogenerated;
	private String who;
	private Date when;
	private Double score;
	private String comments;
	private Long datingid;

	public Boolean getAutogenerated(){ 
		return this.autogenerated;
	}
	public String getWho(){ 
		return this.who;
	}
	public Date getWhen(){ 
		return this.when;
	}
	public Double getScore(){ 
		return this.score;
	}
	public String getComments(){ 
		return this.comments;
	}
	public Long getDatingid(){ 
		return this.datingid;
	}
	public void setAutogenerated(Boolean autogenerated){ 
		this.autogenerated = autogenerated;
	}
	public void setWho(String who){ 
		this.who = who;
	}
	public void setWhen(Date when){ 
		this.when = when;
	}
	public void setScore(Double score){ 
		this.score = score;
	}
	public void setComments(String comments){ 
		this.comments = comments;
	}
	public void setDatingid(Long datingid){ 
		this.datingid = datingid;
	}
}
