//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 09:49:02 AM CLT 
//


package bbr.b2b.regional.logistic.xml.qasn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}I0"/>
 *         &lt;element ref="{}I1"/>
 *         &lt;element ref="{}I2"/>
 *         &lt;element ref="{}I3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "i0",
    "i1",
    "i2",
    "i3"
})
@XmlRootElement(name = "H0")
public class H0 {

    @XmlElement(name = "I0", required = true)
    protected String i0;
    @XmlElement(name = "I1")
    protected int i1;
    @XmlElement(name = "I2")
    protected int i2;
    @XmlElement(name = "I3")
    protected int i3;

    /**
     * Gets the value of the i0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getI0() {
        return i0;
    }

    /**
     * Sets the value of the i0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setI0(String value) {
        this.i0 = value;
    }

    /**
     * Gets the value of the i1 property.
     * 
     */
    public int getI1() {
        return i1;
    }

    /**
     * Sets the value of the i1 property.
     * 
     */
    public void setI1(int value) {
        this.i1 = value;
    }

    /**
     * Gets the value of the i2 property.
     * 
     */
    public int getI2() {
        return i2;
    }

    /**
     * Sets the value of the i2 property.
     * 
     */
    public void setI2(int value) {
        this.i2 = value;
    }

    /**
     * Gets the value of the i3 property.
     * 
     */
    public int getI3() {
        return i3;
    }

    /**
     * Sets the value of the i3 property.
     * 
     */
    public void setI3(int value) {
        this.i3 = value;
    }

}
