//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 09:49:02 AM CLT 
//


package bbr.b2b.regional.logistic.xml.qasn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}K0"/>
 *         &lt;element ref="{}K1"/>
 *         &lt;element ref="{}K2"/>
 *         &lt;element ref="{}K3"/>
 *         &lt;element ref="{}K4"/>
 *         &lt;element ref="{}K5"/>
 *         &lt;element ref="{}K6"/>
 *         &lt;element ref="{}K7"/>
 *         &lt;element ref="{}K8"/>
 *         &lt;element ref="{}K9"/>
 *         &lt;element ref="{}K10"/>
 *         &lt;element ref="{}K11"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "k0",
    "k1",
    "k2",
    "k3",
    "k4",
    "k5",
    "k6",
    "k7",
    "k8",
    "k9",
    "k10",
    "k11"
})
@XmlRootElement(name = "J0")
public class J0 {

    @XmlElement(name = "K0", required = true)
    protected String k0;
    @XmlElement(name = "K1", required = true)
    protected String k1;
    @XmlElement(name = "K2", required = true)
    protected String k2;
    @XmlElement(name = "K3", required = true)
    protected String k3;
    @XmlElement(name = "K4", required = true)
    protected String k4;
    @XmlElement(name = "K5", required = true)
    protected String k5;
    @XmlElement(name = "K6", required = true)
    protected String k6;
    @XmlElement(name = "K7", required = true)
    protected String k7;
    @XmlElement(name = "K8", required = true)
    protected String k8;
    @XmlElement(name = "K9", required = true)
    protected String k9;
    @XmlElement(name = "K10", required = true)
    protected String k10;
    @XmlElement(name = "K11", required = true)
    protected K11 k11;

    /**
     * Gets the value of the k0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK0() {
        return k0;
    }

    /**
     * Sets the value of the k0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK0(String value) {
        this.k0 = value;
    }

    /**
     * Gets the value of the k1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK1() {
        return k1;
    }

    /**
     * Sets the value of the k1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK1(String value) {
        this.k1 = value;
    }

    /**
     * Gets the value of the k2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK2() {
        return k2;
    }

    /**
     * Sets the value of the k2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK2(String value) {
        this.k2 = value;
    }

    /**
     * Gets the value of the k3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK3() {
        return k3;
    }

    /**
     * Sets the value of the k3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK3(String value) {
        this.k3 = value;
    }

    /**
     * Gets the value of the k4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK4() {
        return k4;
    }

    /**
     * Sets the value of the k4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK4(String value) {
        this.k4 = value;
    }

    /**
     * Gets the value of the k5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK5() {
        return k5;
    }

    /**
     * Sets the value of the k5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK5(String value) {
        this.k5 = value;
    }

    /**
     * Gets the value of the k6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK6() {
        return k6;
    }

    /**
     * Sets the value of the k6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK6(String value) {
        this.k6 = value;
    }

    /**
     * Gets the value of the k7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK7() {
        return k7;
    }

    /**
     * Sets the value of the k7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK7(String value) {
        this.k7 = value;
    }

    /**
     * Gets the value of the k8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK8() {
        return k8;
    }

    /**
     * Sets the value of the k8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK8(String value) {
        this.k8 = value;
    }

    /**
     * Gets the value of the k9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK9() {
        return k9;
    }

    /**
     * Sets the value of the k9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK9(String value) {
        this.k9 = value;
    }

    /**
     * Gets the value of the k10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK10() {
        return k10;
    }

    /**
     * Sets the value of the k10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK10(String value) {
        this.k10 = value;
    }

    /**
     * Gets the value of the k11 property.
     * 
     * @return
     *     possible object is
     *     {@link K11 }
     *     
     */
    public K11 getK11() {
        return k11;
    }

    /**
     * Sets the value of the k11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link K11 }
     *     
     */
    public void setK11(K11 value) {
        this.k11 = value;
    }

}
