//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 09:49:02 AM CLT 
//


package bbr.b2b.regional.logistic.xml.qasn;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bbr.b2b.regional.logistic.xml.qasn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _M8_QNAME = new QName("", "M8");
    private final static QName _A1_QNAME = new QName("", "A1");
    private final static QName _M7_QNAME = new QName("", "M7");
    private final static QName _M6_QNAME = new QName("", "M6");
    private final static QName _M11_QNAME = new QName("", "M11");
    private final static QName _M5_QNAME = new QName("", "M5");
    private final static QName _M10_QNAME = new QName("", "M10");
    private final static QName _I0_QNAME = new QName("", "I0");
    private final static QName _M9_QNAME = new QName("", "M9");
    private final static QName _M0_QNAME = new QName("", "M0");
    private final static QName _I3_QNAME = new QName("", "I3");
    private final static QName _E5_QNAME = new QName("", "E5");
    private final static QName _E6_QNAME = new QName("", "E6");
    private final static QName _E7_QNAME = new QName("", "E7");
    private final static QName _I1_QNAME = new QName("", "I1");
    private final static QName _E8_QNAME = new QName("", "E8");
    private final static QName _I2_QNAME = new QName("", "I2");
    private final static QName _M4_QNAME = new QName("", "M4");
    private final static QName _E9_QNAME = new QName("", "E9");
    private final static QName _M3_QNAME = new QName("", "M3");
    private final static QName _M2_QNAME = new QName("", "M2");
    private final static QName _M1_QNAME = new QName("", "M1");
    private final static QName _G13_QNAME = new QName("", "G13");
    private final static QName _E0_QNAME = new QName("", "E0");
    private final static QName _G12_QNAME = new QName("", "G12");
    private final static QName _E2_QNAME = new QName("", "E2");
    private final static QName _E1_QNAME = new QName("", "E1");
    private final static QName _E4_QNAME = new QName("", "E4");
    private final static QName _E3_QNAME = new QName("", "E3");
    private final static QName _G11_QNAME = new QName("", "G11");
    private final static QName _A0_QNAME = new QName("", "A0");
    private final static QName _B5_QNAME = new QName("", "B5");
    private final static QName _B4_QNAME = new QName("", "B4");
    private final static QName _B3_QNAME = new QName("", "B3");
    private final static QName _B2_QNAME = new QName("", "B2");
    private final static QName _B9_QNAME = new QName("", "B9");
    private final static QName _B8_QNAME = new QName("", "B8");
    private final static QName _B7_QNAME = new QName("", "B7");
    private final static QName _B6_QNAME = new QName("", "B6");
    private final static QName _E11_QNAME = new QName("", "E11");
    private final static QName _E10_QNAME = new QName("", "E10");
    private final static QName _B0_QNAME = new QName("", "B0");
    private final static QName _B1_QNAME = new QName("", "B1");
    private final static QName _K1_QNAME = new QName("", "K1");
    private final static QName _K2_QNAME = new QName("", "K2");
    private final static QName _K0_QNAME = new QName("", "K0");
    private final static QName _K9_QNAME = new QName("", "K9");
    private final static QName _B11_QNAME = new QName("", "B11");
    private final static QName _B12_QNAME = new QName("", "B12");
    private final static QName _K7_QNAME = new QName("", "K7");
    private final static QName _K8_QNAME = new QName("", "K8");
    private final static QName _B10_QNAME = new QName("", "B10");
    private final static QName _K5_QNAME = new QName("", "K5");
    private final static QName _G7_QNAME = new QName("", "G7");
    private final static QName _K6_QNAME = new QName("", "K6");
    private final static QName _G8_QNAME = new QName("", "G8");
    private final static QName _K3_QNAME = new QName("", "K3");
    private final static QName _G9_QNAME = new QName("", "G9");
    private final static QName _K4_QNAME = new QName("", "K4");
    private final static QName _G4_QNAME = new QName("", "G4");
    private final static QName _G3_QNAME = new QName("", "G3");
    private final static QName _G6_QNAME = new QName("", "G6");
    private final static QName _G5_QNAME = new QName("", "G5");
    private final static QName _G0_QNAME = new QName("", "G0");
    private final static QName _G2_QNAME = new QName("", "G2");
    private final static QName _G1_QNAME = new QName("", "G1");
    private final static QName _C0_QNAME = new QName("", "C0");
    private final static QName _C1_QNAME = new QName("", "C1");
    private final static QName _C2_QNAME = new QName("", "C2");
    private final static QName _G91_QNAME = new QName("", "G9_1");
    private final static QName _K10_QNAME = new QName("", "K10");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bbr.b2b.regional.logistic.xml.qasn
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link A2 }
     * 
     */
    public A2 createA2() {
        return new A2();
    }

    /**
     * Create an instance of {@link A3 }
     * 
     */
    public A3 createA3() {
        return new A3();
    }

    /**
     * Create an instance of {@link C3 }
     * 
     */
    public C3 createC3() {
        return new C3();
    }

    /**
     * Create an instance of {@link D0 }
     * 
     */
    public D0 createD0() {
        return new D0();
    }

    /**
     * Create an instance of {@link E12 }
     * 
     */
    public E12 createE12() {
        return new E12();
    }

    /**
     * Create an instance of {@link F0 }
     * 
     */
    public F0 createF0() {
        return new F0();
    }

    /**
     * Create an instance of {@link G10 }
     * 
     */
    public G10 createG10() {
        return new G10();
    }

    /**
     * Create an instance of {@link H0 }
     * 
     */
    public H0 createH0() {
        return new H0();
    }

    /**
     * Create an instance of {@link E13 }
     * 
     */
    public E13 createE13() {
        return new E13();
    }

    /**
     * Create an instance of {@link J0 }
     * 
     */
    public J0 createJ0() {
        return new J0();
    }

    /**
     * Create an instance of {@link K11 }
     * 
     */
    public K11 createK11() {
        return new K11();
    }

    /**
     * Create an instance of {@link L0 }
     * 
     */
    public L0 createL0() {
        return new L0();
    }

    /**
     * Create an instance of {@link QASN }
     * 
     */
    public QASN createQASN() {
        return new QASN();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M8")
    public JAXBElement<Double> createM8(Double value) {
        return new JAXBElement<Double>(_M8_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "A1")
    public JAXBElement<Long> createA1(Long value) {
        return new JAXBElement<Long>(_A1_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M7")
    public JAXBElement<Double> createM7(Double value) {
        return new JAXBElement<Double>(_M7_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M6")
    public JAXBElement<String> createM6(String value) {
        return new JAXBElement<String>(_M6_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M11")
    public JAXBElement<Integer> createM11(Integer value) {
        return new JAXBElement<Integer>(_M11_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M5")
    public JAXBElement<String> createM5(String value) {
        return new JAXBElement<String>(_M5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M10")
    public JAXBElement<String> createM10(String value) {
        return new JAXBElement<String>(_M10_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "I0")
    public JAXBElement<String> createI0(String value) {
        return new JAXBElement<String>(_I0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M9")
    public JAXBElement<Double> createM9(Double value) {
        return new JAXBElement<Double>(_M9_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M0")
    public JAXBElement<String> createM0(String value) {
        return new JAXBElement<String>(_M0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "I3")
    public JAXBElement<Integer> createI3(Integer value) {
        return new JAXBElement<Integer>(_I3_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E5")
    public JAXBElement<String> createE5(String value) {
        return new JAXBElement<String>(_E5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E6")
    public JAXBElement<String> createE6(String value) {
        return new JAXBElement<String>(_E6_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E7")
    public JAXBElement<String> createE7(String value) {
        return new JAXBElement<String>(_E7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "I1")
    public JAXBElement<Integer> createI1(Integer value) {
        return new JAXBElement<Integer>(_I1_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E8")
    public JAXBElement<Integer> createE8(Integer value) {
        return new JAXBElement<Integer>(_E8_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "I2")
    public JAXBElement<Integer> createI2(Integer value) {
        return new JAXBElement<Integer>(_I2_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M4")
    public JAXBElement<String> createM4(String value) {
        return new JAXBElement<String>(_M4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E9")
    public JAXBElement<String> createE9(String value) {
        return new JAXBElement<String>(_E9_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M3")
    public JAXBElement<String> createM3(String value) {
        return new JAXBElement<String>(_M3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M2")
    public JAXBElement<String> createM2(String value) {
        return new JAXBElement<String>(_M2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M1")
    public JAXBElement<Integer> createM1(Integer value) {
        return new JAXBElement<Integer>(_M1_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G13")
    public JAXBElement<String> createG13(String value) {
        return new JAXBElement<String>(_G13_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E0")
    public JAXBElement<String> createE0(String value) {
        return new JAXBElement<String>(_E0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G12")
    public JAXBElement<String> createG12(String value) {
        return new JAXBElement<String>(_G12_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E2")
    public JAXBElement<Integer> createE2(Integer value) {
        return new JAXBElement<Integer>(_E2_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E1")
    public JAXBElement<String> createE1(String value) {
        return new JAXBElement<String>(_E1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E4")
    public JAXBElement<String> createE4(String value) {
        return new JAXBElement<String>(_E4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E3")
    public JAXBElement<Double> createE3(Double value) {
        return new JAXBElement<Double>(_E3_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G11")
    public JAXBElement<String> createG11(String value) {
        return new JAXBElement<String>(_G11_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "A0")
    public JAXBElement<String> createA0(String value) {
        return new JAXBElement<String>(_A0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B5")
    public JAXBElement<Integer> createB5(Integer value) {
        return new JAXBElement<Integer>(_B5_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B4")
    public JAXBElement<Integer> createB4(Integer value) {
        return new JAXBElement<Integer>(_B4_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B3")
    public JAXBElement<String> createB3(String value) {
        return new JAXBElement<String>(_B3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B2")
    public JAXBElement<String> createB2(String value) {
        return new JAXBElement<String>(_B2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B9")
    public JAXBElement<String> createB9(String value) {
        return new JAXBElement<String>(_B9_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B8")
    public JAXBElement<String> createB8(String value) {
        return new JAXBElement<String>(_B8_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B7")
    public JAXBElement<String> createB7(String value) {
        return new JAXBElement<String>(_B7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B6")
    public JAXBElement<String> createB6(String value) {
        return new JAXBElement<String>(_B6_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E11")
    public JAXBElement<String> createE11(String value) {
        return new JAXBElement<String>(_E11_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E10")
    public JAXBElement<String> createE10(String value) {
        return new JAXBElement<String>(_E10_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B0")
    public JAXBElement<String> createB0(String value) {
        return new JAXBElement<String>(_B0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B1")
    public JAXBElement<String> createB1(String value) {
        return new JAXBElement<String>(_B1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K1")
    public JAXBElement<String> createK1(String value) {
        return new JAXBElement<String>(_K1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K2")
    public JAXBElement<String> createK2(String value) {
        return new JAXBElement<String>(_K2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K0")
    public JAXBElement<String> createK0(String value) {
        return new JAXBElement<String>(_K0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K9")
    public JAXBElement<String> createK9(String value) {
        return new JAXBElement<String>(_K9_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B11")
    public JAXBElement<Integer> createB11(Integer value) {
        return new JAXBElement<Integer>(_B11_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B12")
    public JAXBElement<String> createB12(String value) {
        return new JAXBElement<String>(_B12_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K7")
    public JAXBElement<String> createK7(String value) {
        return new JAXBElement<String>(_K7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K8")
    public JAXBElement<String> createK8(String value) {
        return new JAXBElement<String>(_K8_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B10")
    public JAXBElement<Integer> createB10(Integer value) {
        return new JAXBElement<Integer>(_B10_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K5")
    public JAXBElement<String> createK5(String value) {
        return new JAXBElement<String>(_K5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G7")
    public JAXBElement<String> createG7(String value) {
        return new JAXBElement<String>(_G7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K6")
    public JAXBElement<String> createK6(String value) {
        return new JAXBElement<String>(_K6_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G8")
    public JAXBElement<String> createG8(String value) {
        return new JAXBElement<String>(_G8_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K3")
    public JAXBElement<String> createK3(String value) {
        return new JAXBElement<String>(_K3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G9")
    public JAXBElement<String> createG9(String value) {
        return new JAXBElement<String>(_G9_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K4")
    public JAXBElement<String> createK4(String value) {
        return new JAXBElement<String>(_K4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G4")
    public JAXBElement<String> createG4(String value) {
        return new JAXBElement<String>(_G4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G3")
    public JAXBElement<String> createG3(String value) {
        return new JAXBElement<String>(_G3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G6")
    public JAXBElement<Integer> createG6(Integer value) {
        return new JAXBElement<Integer>(_G6_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G5")
    public JAXBElement<Double> createG5(Double value) {
        return new JAXBElement<Double>(_G5_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G0")
    public JAXBElement<String> createG0(String value) {
        return new JAXBElement<String>(_G0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G2")
    public JAXBElement<String> createG2(String value) {
        return new JAXBElement<String>(_G2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G1")
    public JAXBElement<String> createG1(String value) {
        return new JAXBElement<String>(_G1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C0")
    public JAXBElement<String> createC0(String value) {
        return new JAXBElement<String>(_C0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C1")
    public JAXBElement<String> createC1(String value) {
        return new JAXBElement<String>(_C1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C2")
    public JAXBElement<String> createC2(String value) {
        return new JAXBElement<String>(_C2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G9_1")
    public JAXBElement<String> createG91(String value) {
        return new JAXBElement<String>(_G91_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K10")
    public JAXBElement<String> createK10(String value) {
        return new JAXBElement<String>(_K10_QNAME, String.class, null, value);
    }

}
