//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 09:49:02 AM CLT 
//


package bbr.b2b.regional.logistic.xml.qasn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}A0"/>
 *         &lt;element ref="{}A1"/>
 *         &lt;element ref="{}A2"/>
 *         &lt;element ref="{}A3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "a0",
    "a1",
    "a2",
    "a3"
})
@XmlRootElement(name = "QASN")
public class QASN {

    @XmlElement(name = "A0", required = true)
    protected String a0;
    @XmlElement(name = "A1")
    protected long a1;
    @XmlElement(name = "A2", required = true)
    protected A2 a2;
    @XmlElement(name = "A3", required = true)
    protected A3 a3;

    /**
     * Gets the value of the a0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA0() {
        return a0;
    }

    /**
     * Sets the value of the a0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA0(String value) {
        this.a0 = value;
    }

    /**
     * Gets the value of the a1 property.
     * 
     */
    public long getA1() {
        return a1;
    }

    /**
     * Sets the value of the a1 property.
     * 
     */
    public void setA1(long value) {
        this.a1 = value;
    }

    /**
     * Gets the value of the a2 property.
     * 
     * @return
     *     possible object is
     *     {@link A2 }
     *     
     */
    public A2 getA2() {
        return a2;
    }

    /**
     * Sets the value of the a2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link A2 }
     *     
     */
    public void setA2(A2 value) {
        this.a2 = value;
    }

    /**
     * Gets the value of the a3 property.
     * 
     * @return
     *     possible object is
     *     {@link A3 }
     *     
     */
    public A3 getA3() {
        return a3;
    }

    /**
     * Sets the value of the a3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link A3 }
     *     
     */
    public void setA3(A3 value) {
        this.a3 = value;
    }

}
